local library = {
    tabs = {},
    buttons = {},
    version = "Exo V3",
    active = true
}
local TS = game:GetService("TweenService")
local UIS = game:GetService("UserInputService")

-- [ScreenGui] --
for i,v in pairs(game:GetService("Lighting"):GetChildren()) do
    if v.Name == "Blur" then
        v:Destroy()
    end
end
if _G["EXOUIName"] == nil then
    _G["EXOUIName"] = game:GetService("HttpService"):GenerateGUID()
end
if game:GetService("CoreGui"):FindFirstChild(_G["EXOUIName"]) then
    game:GetService("CoreGui")[_G["EXOUIName"]]:Destroy()
end
_G["EXOUIName"] = game:GetService("HttpService"):GenerateGUID()
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Parent = game:GetService("CoreGui")
ScreenGui.Enabled = true
ScreenGui.SafeAreaCompatibility = Enum.SafeAreaCompatibility.FullscreenExtension
ScreenGui.Name = _G["EXOUIName"]
ScreenGui.DisplayOrder = 0
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
ScreenGui.ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets
ScreenGui.ClipToDeviceSafeArea = true
ScreenGui.IgnoreGuiInset = true

local ModalFolder = Instance.new("Folder")
ModalFolder.Parent = ScreenGui
-- [Main Frame] --
local frame = Instance.new("ImageButton")
frame.Parent = ScreenGui
frame.LayoutOrder = 0
frame.Active = true
frame.Interactable = true
frame.SizeConstraint = Enum.SizeConstraint.RelativeXY
frame.ZIndex = 1
frame.BorderSizePixel = 0
frame.SliceCenter = Rect.new(0, 0, 0, 0)
frame.Draggable = false
frame.ScaleType = Enum.ScaleType.Crop
frame.Modal = true
frame.AutoButtonColor = false
frame.Transparency = 0.10000000149011612
frame.SelectionOrder = 0
frame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
frame.ImageTransparency = 0.800000011920929
frame.Selectable = true
frame.AnchorPoint = Vector2.new(0.5, 0.5)
frame.Image = "rbxassetid://16255699706"
frame.TileSize = UDim2.new(1, 0, 1, 0)
frame.ImageRectSize = Vector2.new(0, 0)
frame.ImageContent = Content.fromUri("rbxassetid://16255699706")
frame.Selected = false
frame.AutomaticSize = Enum.AutomaticSize.None
frame.Size = UDim2.new(1, 0, 1, 0)
frame.Visible = true
frame.HoverImage = ""
frame.Style = Enum.ButtonStyle.Custom
frame.ClipsDescendants = false
frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
frame.BorderMode = Enum.BorderMode.Outline
frame.ImageColor3 = Color3.fromRGB(255, 255, 255)
frame.PressedImage = ""
frame.Rotation = 0
frame.ImageRectOffset = Vector2.new(0, 0)
frame.BackgroundTransparency = 0.10000000149011612
frame.Position = UDim2.new(0.5, 0, 0.5, 0)
frame.SliceScale = 1
frame.ResampleMode = Enum.ResamplerMode.Default
frame.BorderColor = BrickColor.new("Really black")
frame.Name = "frame"
local scale = Instance.new("UIScale")
scale.Parent = frame
scale.Name = "scale"
scale.Scale = 1
local corner = Instance.new("UICorner")
corner.Parent = frame
corner.Name = "corner"
corner.CornerRadius = UDim.new(0, 0)

-- [Main Page] --
local Main_Frame = Instance.new("CanvasGroup")
Main_Frame.Parent = frame
Main_Frame.LayoutOrder = 0
Main_Frame.GroupTransparency = 0
Main_Frame.BorderMode = Enum.BorderMode.Outline
Main_Frame.Interactable = true
Main_Frame.AnchorPoint = Vector2.new(0.5, 1)
Main_Frame.BorderColor = BrickColor.new("Really black")
Main_Frame.SizeConstraint = Enum.SizeConstraint.RelativeXY
Main_Frame.ZIndex = 1
Main_Frame.AutomaticSize = Enum.AutomaticSize.None
Main_Frame.Size = UDim2.new(1, 0, 1, 0)
Main_Frame.Draggable = false
Main_Frame.Visible = true
Main_Frame.ClipsDescendants = true
Main_Frame.GroupColor3 = Color3.fromRGB(255, 255, 255)
Main_Frame.Name = "Main_Frame"
Main_Frame.SelectionOrder = 0
Main_Frame.Selectable = false
Main_Frame.Rotation = 0
Main_Frame.Transparency = 1
Main_Frame.BackgroundTransparency = 1
Main_Frame.Position = UDim2.new(0.5, 0, 1, 0)
Main_Frame.Active = false
Main_Frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
Main_Frame.BorderSizePixel = 0
Main_Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local scale = Instance.new("UIScale")
scale.Parent = Main_Frame
scale.Name = "scale"
scale.Scale = 1
local padding = Instance.new("UIPadding")
padding.Parent = Main_Frame
padding.PaddingTop = UDim.new(0, 10)
padding.Name = "padding"
padding.PaddingBottom = UDim.new(0, 20)
padding.PaddingLeft = UDim.new(0, 10)
padding.PaddingRight = UDim.new(0, 10)
local scroll = Instance.new("ScrollingFrame")
scroll.Parent = Main_Frame
scroll.LayoutOrder = 0
scroll.Active = true
scroll.Interactable = true
scroll.ScrollingDirection = Enum.ScrollingDirection.Y
scroll.SizeConstraint = Enum.SizeConstraint.RelativeXY
scroll.ZIndex = 0
scroll.BorderSizePixel = 0
scroll.CanvasSize = UDim2.new(0, 0, 0, 0)
scroll.Draggable = false
scroll.MidImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
scroll.CanvasPosition = Vector2.new(0, 0)
scroll.ElasticBehavior = Enum.ElasticBehavior.WhenScrollable
scroll.Transparency = 1
scroll.TopImage = "rbxasset://textures/ui/Scroll/scroll-top.png"
scroll.SelectionOrder = 0
scroll.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
scroll.BorderMode = Enum.BorderMode.Outline
scroll.Selectable = true
scroll.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
scroll.AnchorPoint = Vector2.new(0.5, 1)
scroll.BorderColor = BrickColor.new("Really black")
scroll.AutomaticSize = Enum.AutomaticSize.None
scroll.Size = UDim2.new(1, 0, 1, -100)
scroll.ScrollBarImageColor3 = Color3.fromRGB(255, 255, 255)
scroll.Visible = true
scroll.ClipsDescendants = false
scroll.BorderColor3 = Color3.fromRGB(0, 0, 0)
scroll.ScrollBarThickness = 2
scroll.VerticalScrollBarInset = Enum.ScrollBarInset.None
scroll.ScrollBarImageTransparency = 1
scroll.Rotation = 0
scroll.AutomaticCanvasSize = Enum.AutomaticSize.Y
scroll.BackgroundTransparency = 1
scroll.Position = UDim2.new(0.5, 0, 1, 20)
scroll.ScrollingEnabled = true
scroll.BottomImage = "rbxasset://textures/ui/Scroll/scroll-bottom.png"
scroll.HorizontalScrollBarInset = Enum.ScrollBarInset.None
scroll.Name = "scroll"
local padding = Instance.new("UIPadding")
padding.Parent = scroll
padding.PaddingTop = UDim.new(0, 5)
padding.Name = "padding"
padding.PaddingBottom = UDim.new(0, 20)
padding.PaddingLeft = UDim.new(0, 20)
padding.PaddingRight = UDim.new(0, 20)
local list = Instance.new("UIListLayout")
list.Parent = scroll
list.FillDirection = Enum.FillDirection.Vertical
list.HorizontalAlignment = Enum.HorizontalAlignment.Center
list.HorizontalFlex = Enum.UIFlexAlignment.None
list.VerticalAlignment = Enum.VerticalAlignment.Top
list.SortOrder = Enum.SortOrder.LayoutOrder
list.Name = "list"
list.Wraps = false
list.Padding = UDim.new(0, 0)
list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
list.VerticalFlex = Enum.UIFlexAlignment.None

-- [Tab] --
function library:AdminTab(Title, Description)
    local tab = Instance.new("Frame")
    tab.Parent = scroll
    tab.LayoutOrder = 1
    tab.BorderMode = Enum.BorderMode.Outline
    tab.Interactable = true
    tab.AnchorPoint = Vector2.new(0, 0)
    tab.BorderColor = BrickColor.new("Really black")
    tab.SizeConstraint = Enum.SizeConstraint.RelativeXY
    tab.ZIndex = 1
    tab.AutomaticSize = Enum.AutomaticSize.None
    tab.Size = UDim2.new(1, 0, 0, 150)
    tab.Draggable = false
    tab.Visible = true
    tab.ClipsDescendants = false
    tab.BorderColor3 = Color3.fromRGB(0, 0, 0)
    tab.Selectable = false
    tab.Style = Enum.FrameStyle.Custom
    tab.SelectionOrder = 0
    tab.Rotation = 0
    tab.Transparency = 1
    tab.BackgroundTransparency = 1
    tab.Position = UDim2.new(0, 0, 0, 0)
    tab.Active = false
    tab.Name = "tab"
    tab.BorderSizePixel = 0
    tab.BackgroundColor3 = Color3.fromRGB(0, 0, 0)

    local title = Instance.new("TextLabel")
    title.Parent = tab
    title.LayoutOrder = 0
    title.FontSize = Enum.FontSize.Size28
    title.TextDirection = Enum.TextDirection.Auto
    title.Active = false
    title.Interactable = true
    title.TextTruncate = Enum.TextTruncate.None
    title.SizeConstraint = Enum.SizeConstraint.RelativeXY
    title.ZIndex = 1
    title.BorderSizePixel = 0
    title.Draggable = false
    title.RichText = false
    title.SelectionOrder = 0
    title.TextYAlignment = Enum.TextYAlignment.Top
    title.TextScaled = false
    title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    title.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
    title.BorderMode = Enum.BorderMode.Outline
    title.Selectable = false
    title.OpenTypeFeatures = ""
    title.AnchorPoint = Vector2.new(0, 0.5)
    title.BorderColor = BrickColor.new("Really black")
    title.Visible = true
    title.TextXAlignment = Enum.TextXAlignment.Left
    title.AutomaticSize = Enum.AutomaticSize.None
    title.Size = UDim2.new(0, 150, 1, 0)
    title.TextWrapped = true
    title.TextWrap = true
    title.TextTransparency = 0.20000000298023224
    title.ClipsDescendants = false
    title.BorderColor3 = Color3.fromRGB(0, 0, 0)
    title.Text = Title
    title.TextStrokeColor3 = Color3.fromRGB(255, 0, 0)
    title.TextStrokeTransparency = 0
    title.LineHeight = 1
    title.Rotation = 0
    title.Font = Enum.Font.Unknown
    title.BackgroundTransparency = 1
    title.Position = UDim2.new(0, 0, 0.5, 0)
    title.TextSize = 25
    title.MaxVisibleGraphemes = -1
    title.TextColor3 = Color3.fromRGB(255, 47, 50)
    title.Name = "title"

    local description = Instance.new("TextLabel")
    description.Parent = title
    description.LayoutOrder = 0
    description.FontSize = Enum.FontSize.Size14
    description.TextDirection = Enum.TextDirection.Auto
    description.Active = false
    description.Interactable = true
    description.TextStrokeTransparency = 1
    description.TextTruncate = Enum.TextTruncate.None
    description.SizeConstraint = Enum.SizeConstraint.RelativeXY
    description.ZIndex = 1
    description.BorderSizePixel = 0
    description.Draggable = false
    description.RichText = false
    description.SelectionOrder = 0
    description.TextYAlignment = Enum.TextYAlignment.Top
    description.TextScaled = false
    description.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    description.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    description.BorderMode = Enum.BorderMode.Outline
    description.Selectable = false
    description.OpenTypeFeatures = ""
    description.AnchorPoint = Vector2.new(0, 0)
    description.BorderColor = BrickColor.new("Really black")
    description.Visible = true
    description.TextXAlignment = Enum.TextXAlignment.Left
    description.AutomaticSize = Enum.AutomaticSize.Y
    description.Size = UDim2.new(1, 0, 0, 0)
    description.TextWrapped = true
    description.TextWrap = true
    description.TextTransparency = 0.800000011920929
    description.ClipsDescendants = false
    description.BorderColor3 = Color3.fromRGB(0, 0, 0)
    description.Text = Description
    description.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    description.LineHeight = 1
    description.Rotation = 0
    description.Font = Enum.Font.Unknown
    description.BackgroundTransparency = 1
    description.Position = UDim2.new(0, 0, 0, 55)
    description.TextSize = 14
    description.MaxVisibleGraphemes = -1
    description.TextColor3 = Color3.fromRGB(255, 255, 255)
    description.Name = "description"

    local padding = Instance.new("UIPadding")
    padding.Parent = tab
    padding.PaddingTop = UDim.new(0, 20)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 20)
    padding.PaddingLeft = UDim.new(0, 20)
    padding.PaddingRight = UDim.new(0, 0)

    local tabList = Instance.new("Frame")
    tabList.Parent = tab
    tabList.LayoutOrder = 0
    tabList.BorderMode = Enum.BorderMode.Outline
    tabList.Interactable = true
    tabList.AnchorPoint = Vector2.new(1, 0.5)
    tabList.BorderColor = BrickColor.new("Really black")
    tabList.SizeConstraint = Enum.SizeConstraint.RelativeXY
    tabList.ZIndex = 1
    tabList.AutomaticSize = Enum.AutomaticSize.None
    tabList.Size = UDim2.new(1, -180, 1, 0)
    tabList.Draggable = false
    tabList.Visible = true
    tabList.ClipsDescendants = false
    tabList.BorderColor3 = Color3.fromRGB(0, 0, 0)
    tabList.Selectable = false
    tabList.Style = Enum.FrameStyle.Custom
    tabList.SelectionOrder = 0
    tabList.Rotation = 0
    tabList.Transparency = 1
    tabList.BackgroundTransparency = 1
    tabList.Position = UDim2.new(1, 0, 0.5, 0)
    tabList.Active = false
    tabList.Name = "tabList"
    tabList.BorderSizePixel = 0
    tabList.BackgroundColor3 = Color3.fromRGB(255, 255, 255)

    local list = Instance.new("UIListLayout")
    list.Parent = tabList
    list.FillDirection = Enum.FillDirection.Horizontal
    list.HorizontalAlignment = Enum.HorizontalAlignment.Left
    list.HorizontalFlex = Enum.UIFlexAlignment.None
    list.VerticalAlignment = Enum.VerticalAlignment.Top
    list.SortOrder = Enum.SortOrder.Name
    list.Name = "list"
    list.Wraps = false
    list.Padding = UDim.new(0, 10)
    list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
    list.VerticalFlex = Enum.UIFlexAlignment.None   
    table.insert(library.tabs, tab)
    return tabList
end
function library:Tab(Title, Description)
    local tab = Instance.new("Frame")
    tab.Parent = scroll
    tab.LayoutOrder = 1
    tab.BorderMode = Enum.BorderMode.Outline
    tab.Interactable = true
    tab.AnchorPoint = Vector2.new(0, 0)
    tab.BorderColor = BrickColor.new("Really black")
    tab.SizeConstraint = Enum.SizeConstraint.RelativeXY
    tab.ZIndex = 1
    tab.AutomaticSize = Enum.AutomaticSize.None
    tab.Size = UDim2.new(1, 0, 0, 150)
    tab.Draggable = false
    tab.Visible = true
    tab.ClipsDescendants = false
    tab.BorderColor3 = Color3.fromRGB(0, 0, 0)
    tab.Selectable = false
    tab.Style = Enum.FrameStyle.Custom
    tab.SelectionOrder = 0
    tab.Rotation = 0
    tab.Transparency = 1
    tab.BackgroundTransparency = 1
    tab.Position = UDim2.new(0, 0, 0, 0)
    tab.Active = false
    tab.Name = "tab"
    tab.BorderSizePixel = 0
    tab.BackgroundColor3 = Color3.fromRGB(0, 0, 0)

    local title = Instance.new("TextLabel")
    title.Parent = tab
    title.LayoutOrder = 0
    title.FontSize = Enum.FontSize.Size28
    title.TextDirection = Enum.TextDirection.Auto
    title.Active = false
    title.Interactable = true
    title.TextStrokeTransparency = 1
    title.TextTruncate = Enum.TextTruncate.None
    title.SizeConstraint = Enum.SizeConstraint.RelativeXY
    title.ZIndex = 1
    title.BorderSizePixel = 0
    title.Draggable = false
    title.RichText = false
    title.SelectionOrder = 0
    title.TextYAlignment = Enum.TextYAlignment.Top
    title.TextScaled = false
    title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    title.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
    title.BorderMode = Enum.BorderMode.Outline
    title.Selectable = false
    title.OpenTypeFeatures = ""
    title.AnchorPoint = Vector2.new(0, 0.5)
    title.BorderColor = BrickColor.new("Really black")
    title.Visible = true
    title.TextXAlignment = Enum.TextXAlignment.Left
    title.AutomaticSize = Enum.AutomaticSize.None
    title.Size = UDim2.new(0, 150, 1, 0)
    title.TextWrapped = true
    title.TextWrap = true
    title.TextTransparency = 0.20000000298023224
    title.ClipsDescendants = false
    title.BorderColor3 = Color3.fromRGB(0, 0, 0)
    title.Text = Title
    title.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    title.LineHeight = 1
    title.Rotation = 0
    title.Font = Enum.Font.Unknown
    title.BackgroundTransparency = 1
    title.Position = UDim2.new(0, 0, 0.5, 0)
    title.TextSize = 25
    title.MaxVisibleGraphemes = -1
    title.TextColor3 = Color3.fromRGB(255, 255, 255)
    title.Name = "title"

    local description = Instance.new("TextLabel")
    description.Parent = title
    description.LayoutOrder = 0
    description.FontSize = Enum.FontSize.Size14
    description.TextDirection = Enum.TextDirection.Auto
    description.Active = false
    description.Interactable = true
    description.TextStrokeTransparency = 1
    description.TextTruncate = Enum.TextTruncate.None
    description.SizeConstraint = Enum.SizeConstraint.RelativeXY
    description.ZIndex = 1
    description.BorderSizePixel = 0
    description.Draggable = false
    description.RichText = false
    description.SelectionOrder = 0
    description.TextYAlignment = Enum.TextYAlignment.Top
    description.TextScaled = false
    description.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    description.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    description.BorderMode = Enum.BorderMode.Outline
    description.Selectable = false
    description.OpenTypeFeatures = ""
    description.AnchorPoint = Vector2.new(0, 0)
    description.BorderColor = BrickColor.new("Really black")
    description.Visible = true
    description.TextXAlignment = Enum.TextXAlignment.Left
    description.AutomaticSize = Enum.AutomaticSize.Y
    description.Size = UDim2.new(1, 0, 0, 0)
    description.TextWrapped = true
    description.TextWrap = true
    description.TextTransparency = 0.800000011920929
    description.ClipsDescendants = false
    description.BorderColor3 = Color3.fromRGB(0, 0, 0)
    description.Text = Description
    description.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    description.LineHeight = 1
    description.Rotation = 0
    description.Font = Enum.Font.Unknown
    description.BackgroundTransparency = 1
    description.Position = UDim2.new(0, 0, 0, 55)
    description.TextSize = 14
    description.MaxVisibleGraphemes = -1
    description.TextColor3 = Color3.fromRGB(255, 255, 255)
    description.Name = "description"

    local padding = Instance.new("UIPadding")
    padding.Parent = tab
    padding.PaddingTop = UDim.new(0, 20)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 20)
    padding.PaddingLeft = UDim.new(0, 20)
    padding.PaddingRight = UDim.new(0, 0)

    local tabList = Instance.new("Frame")
    tabList.Parent = tab
    tabList.LayoutOrder = 0
    tabList.BorderMode = Enum.BorderMode.Outline
    tabList.Interactable = true
    tabList.AnchorPoint = Vector2.new(1, 0.5)
    tabList.BorderColor = BrickColor.new("Really black")
    tabList.SizeConstraint = Enum.SizeConstraint.RelativeXY
    tabList.ZIndex = 1
    tabList.AutomaticSize = Enum.AutomaticSize.None
    tabList.Size = UDim2.new(1, -180, 1, 0)
    tabList.Draggable = false
    tabList.Visible = true
    tabList.ClipsDescendants = false
    tabList.BorderColor3 = Color3.fromRGB(0, 0, 0)
    tabList.Selectable = false
    tabList.Style = Enum.FrameStyle.Custom
    tabList.SelectionOrder = 0
    tabList.Rotation = 0
    tabList.Transparency = 1
    tabList.BackgroundTransparency = 1
    tabList.Position = UDim2.new(1, 0, 0.5, 0)
    tabList.Active = false
    tabList.Name = "tabList"
    tabList.BorderSizePixel = 0
    tabList.BackgroundColor3 = Color3.fromRGB(255, 255, 255)

    local list = Instance.new("UIListLayout")
    list.Parent = tabList
    list.FillDirection = Enum.FillDirection.Horizontal
    list.HorizontalAlignment = Enum.HorizontalAlignment.Left
    list.HorizontalFlex = Enum.UIFlexAlignment.None
    list.VerticalAlignment = Enum.VerticalAlignment.Top
    list.SortOrder = Enum.SortOrder.Name
    list.Name = "list"
    list.Wraps = false
    list.Padding = UDim.new(0, 10)
    list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
    list.VerticalFlex = Enum.UIFlexAlignment.None   
    table.insert(library.tabs, tab)
    return tabList
end

local Lucide = loadstring(game:HttpGet("https://raw.githubusercontent.com/Eclipse-SS/WindUI/refs/heads/main/src/icons/lucide.lua"))()

local Spritesheets = Lucide.Spritesheets
local IconLibrary = Lucide.Icons

local function isIcon(value)
	return type(value) == "table" and getmetatable(value) and getmetatable(value).__type == "Icon"
end

function library:Button(TabList, Icon, Text, Callback)
    if not isIcon(Icon) then return end
    local tabButton = Instance.new("ImageButton")
    tabButton.Parent = TabList
    tabButton.LayoutOrder = 0
    tabButton.Active = true
    tabButton.Interactable = true
    tabButton.SizeConstraint = Enum.SizeConstraint.RelativeXY
    tabButton.ZIndex = 1
    tabButton.BorderSizePixel = 0
    tabButton.SliceCenter = Rect.new(0, 0, 0, 0)
    tabButton.Draggable = false
    tabButton.ScaleType = Enum.ScaleType.Stretch
    tabButton.Modal = false
    tabButton.AutoButtonColor = false
    tabButton.Transparency = 0.699999988079071
    tabButton.SelectionOrder = 0
    tabButton.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    tabButton.ImageTransparency = 0
    tabButton.Selectable = true
    tabButton.AnchorPoint = Vector2.new(0, 0)
    tabButton.Image = ""
    tabButton.TileSize = UDim2.new(1, 0, 1, 0)
    tabButton.ImageRectSize = Vector2.new(0, 0)
    tabButton.ImageContent = Content.none
    tabButton.Selected = false
    tabButton.AutomaticSize = Enum.AutomaticSize.None
    tabButton.Size = UDim2.new(0.3330000042915344, -7, 1, 0)
    tabButton.Visible = true
    tabButton.HoverImage = ""
    tabButton.Style = Enum.ButtonStyle.Custom
    tabButton.ClipsDescendants = false
    tabButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
    tabButton.BorderMode = Enum.BorderMode.Outline
    tabButton.ImageColor3 = Color3.fromRGB(255, 255, 255)
    tabButton.PressedImage = ""
    tabButton.Rotation = 0
    tabButton.ImageRectOffset = Vector2.new(0, 0)
    tabButton.BackgroundTransparency = 0.699999988079071
    tabButton.Position = UDim2.new(0, 0, 0, 0)
    tabButton.SliceScale = 1
    tabButton.ResampleMode = Enum.ResamplerMode.Default
    tabButton.BorderColor = BrickColor.new("Really black")
    tabButton.Name = "tabButton"
    local corner = Instance.new("UICorner")
    corner.Parent = tabButton
    corner.Name = "corner"
    corner.CornerRadius = UDim.new(0, 10)
    local list = Instance.new("UIListLayout")
    list.Parent = tabButton
    list.FillDirection = Enum.FillDirection.Vertical
    list.HorizontalAlignment = Enum.HorizontalAlignment.Center
    list.HorizontalFlex = Enum.UIFlexAlignment.None
    list.VerticalAlignment = Enum.VerticalAlignment.Center
    list.SortOrder = Enum.SortOrder.LayoutOrder
    list.Name = "list"
    list.Wraps = false
    list.Padding = UDim.new(0, 12)
    list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
    list.VerticalFlex = Enum.UIFlexAlignment.None
    local padding = Instance.new("UIPadding")
    padding.Parent = tabButton
    padding.PaddingTop = UDim.new(0, 10)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 10)
    padding.PaddingLeft = UDim.new(0, 15)
    padding.PaddingRight = UDim.new(0, 15)
    local icon = Instance.new("ImageLabel")
    icon.Parent = tabButton
    icon.LayoutOrder = 0
    icon.Active = false
    icon.Interactable = true
    icon.SizeConstraint = Enum.SizeConstraint.RelativeXY
    icon.ZIndex = 1
    icon.BorderSizePixel = 0
    icon.SliceCenter = Rect.new(0, 0, 0, 0)
    icon.Draggable = false
    icon.ScaleType = Enum.ScaleType.Fit
    icon.Transparency = 1
    icon.SelectionOrder = 0
    icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    icon.ImageTransparency = 0.20000000298023224
    icon.Selectable = false
    icon.AnchorPoint = Vector2.new(0, 0)
    print(Icon)
    if Icon.Type == "NamedIcon" then
		print("Using named icon:", Icon.Name)
        local iconDef = Icon.Definition
        Icon = Spritesheets[iconDef.Image]
        icon.ImageRectSize = iconDef.ImageRectSize
        icon.ImageRectOffset = iconDef.ImageRectPosition
	else
		print("Using asset id:", Icon.Id)
        Icon = "rbxassetid://"..Icon.Id
	end
    icon.Image = Icon
    icon.TileSize = UDim2.new(1, 0, 1, 0)
    icon.BorderColor = BrickColor.new("Really black")
    icon.ImageContent = Content.fromUri(Icon)
    icon.AutomaticSize = Enum.AutomaticSize.None
    icon.Size = UDim2.new(0, 30, 0, 30)
    icon.ClipsDescendants = false
    icon.BorderColor3 = Color3.fromRGB(0, 0, 0)
    icon.Visible = true
    icon.ImageColor3 = Color3.fromRGB(255, 255, 255)
    icon.BorderMode = Enum.BorderMode.Outline
    icon.Rotation = 0
    icon.ImageRectOffset = Vector2.new(0, 0)
    icon.BackgroundTransparency = 1
    icon.Position = UDim2.new(0, 0, 0, 0)
    icon.SliceScale = 1
    icon.ImageRectSize = Vector2.new(0, 0)
    icon.ResampleMode = Enum.ResamplerMode.Default
    icon.Name = "icon"
    local label = Instance.new("TextLabel")
    label.Parent = tabButton
    label.LayoutOrder = 0
    label.FontSize = Enum.FontSize.Size14
    label.TextDirection = Enum.TextDirection.Auto
    label.Active = false
    label.Interactable = true
    label.TextStrokeTransparency = 1
    label.TextTruncate = Enum.TextTruncate.None
    label.SizeConstraint = Enum.SizeConstraint.RelativeXY
    label.ZIndex = 1
    label.BorderSizePixel = 0
    label.Draggable = false
    label.RichText = false
    label.SelectionOrder = 0
    label.TextYAlignment = Enum.TextYAlignment.Center
    label.TextScaled = false
    label.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    label.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
    label.BorderMode = Enum.BorderMode.Outline
    label.Selectable = false
    label.OpenTypeFeatures = ""
    label.AnchorPoint = Vector2.new(0, 0)
    label.BorderColor = BrickColor.new("Really black")
    label.Visible = true
    label.TextXAlignment = Enum.TextXAlignment.Center
    label.AutomaticSize = Enum.AutomaticSize.None
    label.Size = UDim2.new(1, 0, 0, 10)
    label.TextWrapped = true
    label.TextWrap = true
    label.TextTransparency = 0.20000000298023224
    label.ClipsDescendants = false
    label.BorderColor3 = Color3.fromRGB(0, 0, 0)
    label.Text = Text
    label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    label.LineHeight = 1
    label.Rotation = 0
    label.Font = Enum.Font.Unknown
    label.BackgroundTransparency = 1
    label.Position = UDim2.new(0, 0, 0, 0)
    label.TextSize = 14
    label.MaxVisibleGraphemes = -1
    label.TextColor3 = Color3.fromRGB(255, 255, 255)
    label.Name = "label"

    tabButton.MouseEnter:Connect(function()
        if _G["Modal_Open"] ~= true then
            game:GetService("TweenService"):Create(tabButton, TweenInfo.new(0.2), {BackgroundColor3=Color3.fromRGB(125, 125, 125)}):Play()
        end
    end)
    tabButton.MouseLeave:Connect(function()
        if _G["Modal_Open"] ~= true then
            game:GetService("TweenService"):Create(tabButton, TweenInfo.new(0.2), {BackgroundColor3=Color3.fromRGB(0, 0, 0)}):Play()
        end
    end)
    table.insert(library.buttons, tabButton)
    tabButton.MouseButton1Down:Connect(function() Callback() end)
end


-- [Navigation]
local navigation_buttons = Instance.new("Frame")
navigation_buttons.Parent = Main_Frame
navigation_buttons.LayoutOrder = 0
navigation_buttons.BorderMode = Enum.BorderMode.Outline
navigation_buttons.Interactable = true
navigation_buttons.AnchorPoint = Vector2.new(0, 0)
navigation_buttons.BorderColor = BrickColor.new("Really black")
navigation_buttons.SizeConstraint = Enum.SizeConstraint.RelativeXY
navigation_buttons.ZIndex = 1
navigation_buttons.AutomaticSize = Enum.AutomaticSize.None
navigation_buttons.Size = UDim2.new(0, 90, 0, 40)
navigation_buttons.Draggable = false
navigation_buttons.Visible = true
navigation_buttons.ClipsDescendants = false
navigation_buttons.BorderColor3 = Color3.fromRGB(0, 0, 0)
navigation_buttons.Selectable = false
navigation_buttons.Style = Enum.FrameStyle.Custom
navigation_buttons.SelectionOrder = 0
navigation_buttons.Rotation = 0
navigation_buttons.Transparency = 1
navigation_buttons.BackgroundTransparency = 1
navigation_buttons.Position = UDim2.new(0, 20, 0, 60)
navigation_buttons.Active = false
navigation_buttons.Name = "navigation_buttons"
navigation_buttons.BorderSizePixel = 0
navigation_buttons.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local list = Instance.new("UIListLayout")
list.Parent = navigation_buttons
list.FillDirection = Enum.FillDirection.Horizontal
list.HorizontalAlignment = Enum.HorizontalAlignment.Left
list.HorizontalFlex = Enum.UIFlexAlignment.None
list.VerticalAlignment = Enum.VerticalAlignment.Top
list.SortOrder = Enum.SortOrder.LayoutOrder
list.Name = "list"
list.Wraps = false
list.Padding = UDim.new(0, 10)
list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
list.VerticalFlex = Enum.UIFlexAlignment.None
local close = Instance.new("ImageButton")
close.Parent = navigation_buttons
close.LayoutOrder = 0
close.Active = true
close.Interactable = true
close.SizeConstraint = Enum.SizeConstraint.RelativeXY
close.ZIndex = 1
close.BorderSizePixel = 0
close.SliceCenter = Rect.new(0, 0, 0, 0)
close.Draggable = false
close.ScaleType = Enum.ScaleType.Stretch
close.Modal = false
close.AutoButtonColor = false
close.Transparency = 0.8999999761581421
close.SelectionOrder = 0
close.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
close.ImageTransparency = 0
close.Selectable = true
close.AnchorPoint = Vector2.new(0, 0)
close.Image = ""
close.TileSize = UDim2.new(1, 0, 1, 0)
close.ImageRectSize = Vector2.new(0, 0)
close.ImageContent = Content.none
close.Selected = false
close.AutomaticSize = Enum.AutomaticSize.None
close.Size = UDim2.new(0, 40, 0, 40)
close.Visible = true
close.HoverImage = ""
close.Style = Enum.ButtonStyle.Custom
close.ClipsDescendants = false
close.BorderColor3 = Color3.fromRGB(0, 0, 0)
close.BorderMode = Enum.BorderMode.Outline
close.ImageColor3 = Color3.fromRGB(255, 255, 255)
close.PressedImage = ""
close.Rotation = 0
close.ImageRectOffset = Vector2.new(0, 0)
close.BackgroundTransparency = 0.8999999761581421
close.Position = UDim2.new(0, 0, 0, 0)
close.SliceScale = 1
close.ResampleMode = Enum.ResamplerMode.Default
close.BorderColor = BrickColor.new("Really black")
close.Name = "close"

close.MouseEnter:Connect(function()
    game:GetService("TweenService"):Create(close, TweenInfo.new(0.2), {BackgroundColor3=Color3.fromRGB(125, 125, 125)}):Play()
end)
close.MouseLeave:Connect(function()
    game:GetService("TweenService"):Create(close, TweenInfo.new(0.2), {BackgroundColor3=Color3.fromRGB(255, 255, 255)}):Play()
end)
close.MouseButton1Down:Connect(function() library:CloseUI() end)

local corner = Instance.new("UICorner")
corner.Parent = close
corner.Name = "corner"
corner.CornerRadius = UDim.new(1, 0)
local icon = Instance.new("ImageLabel")
icon.Parent = close
icon.LayoutOrder = 0
icon.Active = false
icon.Interactable = true
icon.SizeConstraint = Enum.SizeConstraint.RelativeXY
icon.ZIndex = 1
icon.BorderSizePixel = 0
icon.SliceCenter = Rect.new(0, 0, 0, 0)
icon.Draggable = false
icon.ScaleType = Enum.ScaleType.Stretch
icon.Transparency = 1
icon.SelectionOrder = 0
icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
icon.ImageTransparency = 0
icon.Selectable = false
icon.AnchorPoint = Vector2.new(0.5, 0.5)
icon.Image = "rbxassetid://11293981586"
icon.TileSize = UDim2.new(1, 0, 1, 0)
icon.BorderColor = BrickColor.new("Really black")
icon.ImageContent = Content.fromUri("rbxassetid://11293981586")
icon.AutomaticSize = Enum.AutomaticSize.None
icon.Size = UDim2.new(0.44999998807907104, 0, 0.44999998807907104, 0)
icon.ClipsDescendants = false
icon.BorderColor3 = Color3.fromRGB(0, 0, 0)
icon.Visible = true
icon.ImageColor3 = Color3.fromRGB(255, 255, 255)
icon.BorderMode = Enum.BorderMode.Outline
icon.Rotation = 0
icon.ImageRectOffset = Vector2.new(0, 0)
icon.BackgroundTransparency = 1
icon.Position = UDim2.new(0.5, 0, 0.5, 0)
icon.SliceScale = 1
icon.ImageRectSize = Vector2.new(0, 0)
icon.ResampleMode = Enum.ResamplerMode.Default
icon.Name = "icon"
local scale = Instance.new("UIScale")
scale.Parent = icon
scale.Name = "scale"
scale.Scale = 1
local gradient = Instance.new("UIGradient")
gradient.Parent = close
gradient.Offset = Vector2.new(0, 0)
gradient.Transparency =
    NumberSequence.new({NumberSequenceKeypoint.new(0, 0, 0), NumberSequenceKeypoint.new(1, 0.33125001192092896, 0)})
gradient.Name = "gradient"
gradient.Color =
    ColorSequence.new(
    {
        ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))
    }
)
gradient.Rotation = 0
gradient.Enabled = false
local header = Instance.new("TextLabel")
header.Parent = Main_Frame
header.LayoutOrder = 0
header.FontSize = Enum.FontSize.Size24
header.TextDirection = Enum.TextDirection.Auto
header.Active = false
header.Interactable = true
header.TextStrokeTransparency = 1
header.TextTruncate = Enum.TextTruncate.None
header.SizeConstraint = Enum.SizeConstraint.RelativeXY
header.ZIndex = 1
header.BorderSizePixel = 0
header.Draggable = false
header.RichText = false
header.SelectionOrder = 0
header.TextYAlignment = Enum.TextYAlignment.Center
header.TextScaled = false
header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
header.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal)
header.BorderMode = Enum.BorderMode.Outline
header.Selectable = false
header.OpenTypeFeatures = ""
header.AnchorPoint = Vector2.new(0.5, 0)
header.BorderColor = BrickColor.new("Really black")
header.Visible = true
header.TextXAlignment = Enum.TextXAlignment.Center
header.AutomaticSize = Enum.AutomaticSize.None
header.Size = UDim2.new(1, 0, 0, 40)
header.TextWrapped = false
header.TextWrap = false
header.TextTransparency = 0.10000000149011612
header.ClipsDescendants = false
header.BorderColor3 = Color3.fromRGB(0, 0, 0)
header.Text = library.version
header.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
header.LineHeight = 1
header.Rotation = 0
header.Font = Enum.Font.Unknown
header.BackgroundTransparency = 1
header.Position = UDim2.new(0.5, 0, 0, 20)
header.TextSize = 22
header.MaxVisibleGraphemes = -1
header.TextColor3 = Color3.fromRGB(255, 255, 255)
header.Name = "header"
local shadow = Instance.new("ImageLabel")
shadow.Parent = frame
shadow.LayoutOrder = 0
shadow.Active = false
shadow.Interactable = true
shadow.SizeConstraint = Enum.SizeConstraint.RelativeXY
shadow.ZIndex = -10
shadow.BorderSizePixel = 0
shadow.SliceCenter = Rect.new(512, 512, 512, 512)
shadow.Draggable = false
shadow.ScaleType = Enum.ScaleType.Slice
shadow.Transparency = 1
shadow.SelectionOrder = 0
shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
shadow.ImageTransparency = 0
shadow.Selectable = false
shadow.AnchorPoint = Vector2.new(0.5, 0.5)
shadow.Image = "rbxassetid://16286730454"
shadow.TileSize = UDim2.new(1, 0, 1, 0)
shadow.BorderColor = BrickColor.new("Really black")
shadow.ImageContent = Content.fromUri("rbxassetid://16286730454")
shadow.AutomaticSize = Enum.AutomaticSize.None
shadow.Size = UDim2.new(1, 88, 1, 88)
shadow.ClipsDescendants = false
shadow.BorderColor3 = Color3.fromRGB(0, 0, 0)
shadow.Visible = false
shadow.ImageColor3 = Color3.fromRGB(255, 255, 255)
shadow.BorderMode = Enum.BorderMode.Outline
shadow.Rotation = 0.00009999999747378752
shadow.ImageRectOffset = Vector2.new(0, 0)
shadow.BackgroundTransparency = 1
shadow.Position = UDim2.new(0.5, 0, 0.5, 0)
shadow.SliceScale = 0.1899999976158142
shadow.ImageRectSize = Vector2.new(0, 0)
shadow.ResampleMode = Enum.ResamplerMode.Default
shadow.Name = "shadow"
local scale = Instance.new("UIScale")
scale.Parent = ScreenGui
scale.Name = "scale"
scale.Scale = 1

function library:modal(Title, Description, Icon, RawIcon)
    if not isIcon(Icon) then return end
    local modal_panel = Instance.new("ImageButton")
    modal_panel.Parent = ModalFolder
    modal_panel.LayoutOrder = 0
    modal_panel.Active = true
    modal_panel.Interactable = true
    modal_panel.SizeConstraint = Enum.SizeConstraint.RelativeXY
    modal_panel.ZIndex = 3
    modal_panel.BorderSizePixel = 0
    modal_panel.SliceCenter = Rect.new(0, 0, 0, 0)
    modal_panel.Draggable = false
    modal_panel.ScaleType = Enum.ScaleType.Stretch
    modal_panel.Modal = false
    modal_panel.AutoButtonColor = false
    modal_panel.Transparency = 1
    modal_panel.SelectionOrder = 0
    modal_panel.BackgroundColor3 = Color3.fromRGB(76, 76, 76)
    modal_panel.ImageTransparency = 0.5
    modal_panel.Selectable = true
    modal_panel.AnchorPoint = Vector2.new(0.5, 0.5)
    modal_panel.Image = "rbxassetid://16286761786"
    modal_panel.TileSize = UDim2.new(1, 0, 1, 0)
    modal_panel.ImageRectSize = Vector2.new(0, 0)
    modal_panel.ImageContent = Content.fromUri("rbxassetid://16286761786")
    modal_panel.Selected = false
    modal_panel.AutomaticSize = Enum.AutomaticSize.None
    modal_panel.Size = UDim2.new(1, 0, 1, 0)
    modal_panel.Visible = true
    modal_panel.HoverImage = ""
    modal_panel.Style = Enum.ButtonStyle.Custom
    modal_panel.ClipsDescendants = false
    modal_panel.BorderColor3 = Color3.fromRGB(0, 0, 0)
    modal_panel.BorderMode = Enum.BorderMode.Outline
    modal_panel.ImageColor3 = Color3.fromRGB(255, 255, 255)
    modal_panel.PressedImage = ""
    modal_panel.Rotation = 0
    modal_panel.ImageRectOffset = Vector2.new(0, 0)
    modal_panel.BackgroundTransparency = 1
    modal_panel.Position = UDim2.new(0.5, 0, 0.5, 0)
    modal_panel.SliceScale = 1
    modal_panel.ResampleMode = Enum.ResamplerMode.Default
    modal_panel.BorderColor = BrickColor.new("Really black")
    modal_panel.Name = "modal_panel"
    local scale = Instance.new("UIScale")
    scale.Parent = modal_panel
    scale.Name = "scale"
    scale.Scale = 0
    modal_panel.ImageTransparency = 1
    game:GetService("TweenService"):Create(modal_panel.scale, TweenInfo.new(0.3), {Scale=1}):Play()
    game:GetService("TweenService"):Create(modal_panel, TweenInfo.new(1.5), {ImageTransparency=0.5}):Play()
    local frame = Instance.new("ImageButton")
    frame.Parent = modal_panel
    frame.LayoutOrder = 0
    frame.Active = true
    frame.Interactable = true
    frame.SizeConstraint = Enum.SizeConstraint.RelativeXY
    frame.ZIndex = 1
    frame.BorderSizePixel = 0
    frame.SliceCenter = Rect.new(512, 512, 512, 512)
    frame.Draggable = false
    frame.ScaleType = Enum.ScaleType.Slice
    frame.Modal = false
    frame.AutoButtonColor = false
    frame.Transparency = 1
    frame.SelectionOrder = 0
    frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    frame.ImageTransparency = 0.10000000149011612
    frame.Selectable = false
    frame.AnchorPoint = Vector2.new(0.5, 0.5)
    frame.Image = "rbxassetid://16286719854"
    frame.TileSize = UDim2.new(1, 0, 1, 0)
    frame.ImageRectSize = Vector2.new(0, 0)
    frame.ImageContent = Content.fromUri("rbxassetid://16286719854")
    frame.Selected = false
    frame.AutomaticSize = Enum.AutomaticSize.None
    frame.Size = UDim2.new(0.10000000149011612, 300, 0.5, 160)
    frame.Visible = true
    frame.HoverImage = ""
    frame.Style = Enum.ButtonStyle.Custom
    frame.ClipsDescendants = true
    frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
    frame.BorderMode = Enum.BorderMode.Outline
    frame.ImageColor3 = Color3.fromRGB(70, 70, 70)
    frame.PressedImage = ""
    frame.Rotation = 0
    frame.ImageRectOffset = Vector2.new(0, 0)
    frame.BackgroundTransparency = 1
    frame.Position = UDim2.new(0.5, 0, 0.5, 0)
    frame.SliceScale = 0.10000000149011612
    frame.ResampleMode = Enum.ResamplerMode.Default
    frame.BorderColor = BrickColor.new("Really black")
    frame.Name = "frame"
    local shadow = Instance.new("ImageLabel")
    shadow.Parent = frame
    shadow.LayoutOrder = 0
    shadow.Active = false
    shadow.Interactable = true
    shadow.SizeConstraint = Enum.SizeConstraint.RelativeXY
    shadow.ZIndex = -10
    shadow.BorderSizePixel = 0
    shadow.SliceCenter = Rect.new(512, 512, 512, 512)
    shadow.Draggable = false
    shadow.ScaleType = Enum.ScaleType.Slice
    shadow.Transparency = 1
    shadow.SelectionOrder = 0
    shadow.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    shadow.ImageTransparency = 0.5
    shadow.Selectable = false
    shadow.AnchorPoint = Vector2.new(0.5, 0.5)
    shadow.Image = "rbxassetid://16286730454"
    shadow.TileSize = UDim2.new(1, 0, 1, 0)
    shadow.BorderColor = BrickColor.new("Really black")
    shadow.ImageContent = Content.fromUri("rbxassetid://16286730454")
    shadow.AutomaticSize = Enum.AutomaticSize.None
    shadow.Size = UDim2.new(1, 110, 1, 110)
    shadow.ClipsDescendants = false
    shadow.BorderColor3 = Color3.fromRGB(0, 0, 0)
    shadow.Visible = true
    shadow.ImageColor3 = Color3.fromRGB(255, 255, 255)
    shadow.BorderMode = Enum.BorderMode.Outline
    shadow.Rotation = 0.00009999999747378752
    shadow.ImageRectOffset = Vector2.new(0, 0)
    shadow.BackgroundTransparency = 1
    shadow.Position = UDim2.new(0.5, 0, 0.5, 0)
    shadow.SliceScale = 0.1899999976158142
    shadow.ImageRectSize = Vector2.new(0, 0)
    shadow.ResampleMode = Enum.ResamplerMode.Default
    shadow.Name = "shadow"
    local prism = Instance.new("ImageLabel")
    prism.Parent = frame
    prism.LayoutOrder = 0
    prism.Active = false
    prism.Interactable = true
    prism.SizeConstraint = Enum.SizeConstraint.RelativeXY
    prism.ZIndex = -10
    prism.BorderSizePixel = 0
    prism.SliceCenter = Rect.new(512, 512, 512, 512)
    prism.Draggable = false
    prism.ScaleType = Enum.ScaleType.Crop
    prism.Transparency = 1
    prism.SelectionOrder = 0
    prism.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    prism.ImageTransparency = 0.800000011920929
    prism.Selectable = false
    prism.AnchorPoint = Vector2.new(0.5, 0.5)
    prism.Image = "rbxassetid://16255699706"
    prism.TileSize = UDim2.new(1, 0, 1, 0)
    prism.BorderColor = BrickColor.new("Really black")
    prism.ImageContent = Content.fromUri("rbxassetid://16255699706")
    prism.AutomaticSize = Enum.AutomaticSize.None
    prism.Size = UDim2.new(1, 20, 1, 20)
    prism.ClipsDescendants = false
    prism.BorderColor3 = Color3.fromRGB(0, 0, 0)
    prism.Visible = true
    prism.ImageColor3 = Color3.fromRGB(143, 143, 143)
    prism.BorderMode = Enum.BorderMode.Outline
    prism.Rotation = 0.00009999999747378752
    prism.ImageRectOffset = Vector2.new(0, 0)
    prism.BackgroundTransparency = 1
    prism.Position = UDim2.new(0.5, 0, 0.5, 0)
    prism.SliceScale = 0.1899999976158142
    prism.ImageRectSize = Vector2.new(0, 0)
    prism.ResampleMode = Enum.ResamplerMode.Default
    prism.Name = "prism"
    local corner = Instance.new("UICorner")
    corner.Parent = prism
    corner.Name = "corner"
    corner.CornerRadius = UDim.new(0, 27)
    local stroke = Instance.new("UIStroke")
    stroke.Parent = prism
    stroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual
    stroke.LineJoinMode = Enum.LineJoinMode.Round
    stroke.Name = "stroke"
    stroke.Color = Color3.fromRGB(255, 255, 255)
    stroke.Transparency = 0.8500000238418579
    stroke.Thickness = 1
    stroke.Enabled = true
    local padding = Instance.new("UIPadding")
    padding.Parent = frame
    padding.PaddingTop = UDim.new(0, 10)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 10)
    padding.PaddingLeft = UDim.new(0, 10)
    padding.PaddingRight = UDim.new(0, 10)
    local scroll = Instance.new("ScrollingFrame")
    scroll.Parent = frame
    scroll.LayoutOrder = 0
    scroll.Active = true
    scroll.Interactable = true
    scroll.ScrollingDirection = Enum.ScrollingDirection.Y
    scroll.SizeConstraint = Enum.SizeConstraint.RelativeXY
    scroll.ZIndex = 1
    scroll.BorderSizePixel = 0
    scroll.CanvasSize = UDim2.new(0, 0, 0, 0)
    scroll.Draggable = false
    scroll.MidImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
    scroll.CanvasPosition = Vector2.new(0, 0)
    scroll.ElasticBehavior = Enum.ElasticBehavior.WhenScrollable
    scroll.Transparency = 1
    scroll.TopImage = "rbxasset://textures/ui/Scroll/scroll-top.png"
    scroll.SelectionOrder = 0
    scroll.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    scroll.BorderMode = Enum.BorderMode.Outline
    scroll.Selectable = true
    scroll.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
    scroll.AnchorPoint = Vector2.new(0.5, 1)
    scroll.BorderColor = BrickColor.new("Really black")
    scroll.AutomaticSize = Enum.AutomaticSize.None
    scroll.Size = UDim2.new(1, 0, 1, -60)
    scroll.ScrollBarImageColor3 = Color3.fromRGB(255, 255, 255)
    scroll.Visible = true
    scroll.ClipsDescendants = false
    scroll.BorderColor3 = Color3.fromRGB(0, 0, 0)
    scroll.ScrollBarThickness = 2
    scroll.VerticalScrollBarInset = Enum.ScrollBarInset.None
    scroll.ScrollBarImageTransparency = 0.800000011920929
    scroll.Rotation = 0
    scroll.AutomaticCanvasSize = Enum.AutomaticSize.Y
    scroll.BackgroundTransparency = 1
    scroll.Position = UDim2.new(0.5, 0, 1, -10)
    scroll.ScrollingEnabled = true
    scroll.BottomImage = "rbxasset://textures/ui/Scroll/scroll-bottom.png"
    scroll.HorizontalScrollBarInset = Enum.ScrollBarInset.None
    scroll.Name = "scroll"
    local details = Instance.new("Frame")
    details.Parent = scroll
    details.LayoutOrder = 1
    details.BorderMode = Enum.BorderMode.Outline
    details.Interactable = true
    details.AnchorPoint = Vector2.new(0, 0)
    details.BorderColor = BrickColor.new("Really black")
    details.SizeConstraint = Enum.SizeConstraint.RelativeXY
    details.ZIndex = 1
    details.AutomaticSize = Enum.AutomaticSize.None
    details.Size = UDim2.new(1, 0, 0, 170)
    details.Draggable = false
    details.Visible = true
    details.ClipsDescendants = false
    details.BorderColor3 = Color3.fromRGB(0, 0, 0)
    details.Selectable = false
    details.Style = Enum.FrameStyle.Custom
    details.SelectionOrder = 0
    details.Rotation = 0
    details.Transparency = 1
    details.BackgroundTransparency = 1
    details.Position = UDim2.new(0, 0, 0, 0)
    details.Active = false
    details.Name = "details"
    details.BorderSizePixel = 0
    details.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    local profile = Instance.new("ImageLabel")
    profile.Parent = details
    profile.LayoutOrder = 0
    profile.Active = false
    profile.Interactable = true
    profile.SizeConstraint = Enum.SizeConstraint.RelativeXY
    profile.ZIndex = 1
    profile.BorderSizePixel = 0
    profile.SliceCenter = Rect.new(0, 0, 0, 0)
    profile.Draggable = false
    profile.ScaleType = Enum.ScaleType.Fit
    profile.Transparency = 0.800000011920929
    profile.SelectionOrder = 0
    profile.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    profile.ImageTransparency = 0
    profile.Selectable = false
    profile.AnchorPoint = Vector2.new(0, 0)
    if Icon.Type == "NamedIcon" then
		print("Using named icon:", Icon.Name)
        local iconDef = Icon.Definition
        Icon = Spritesheets[iconDef.Image]
        icon.ImageRectSize = iconDef.ImageRectSize
        icon.ImageRectOffset = iconDef.ImageRectPosition
	else
		print("Using asset id:", Icon.Id)
        Icon = "rbxassetid://"..Icon.Id
	end
    profile.Image = Icon
    profile.TileSize = UDim2.new(1, 0, 1, 0)
    profile.BorderColor = BrickColor.new("Really black")
    profile.ImageContent = Content.fromUri(Icon)
    profile.AutomaticSize = Enum.AutomaticSize.None
    profile.Size = UDim2.new(0, 100, 0, 100)
    profile.ClipsDescendants = false
    profile.BorderColor3 = Color3.fromRGB(0, 0, 0)
    profile.Visible = true
    profile.ImageColor3 = Color3.fromRGB(255, 255, 255)
    profile.BorderMode = Enum.BorderMode.Outline
    profile.Rotation = 0
    profile.ImageRectOffset = Vector2.new(0, 0)
    profile.BackgroundTransparency = 0.800000011920929
    profile.Position = UDim2.new(0, 0, 0, 0)
    profile.SliceScale = 1
    profile.ImageRectSize = Vector2.new(0, 0)
    profile.ResampleMode = Enum.ResamplerMode.Default
    profile.Name = "profile"
    local corner = Instance.new("UICorner")
    corner.Parent = profile
    corner.Name = "corner"
    corner.CornerRadius = UDim.new(1, 0)
    local list = Instance.new("UIListLayout")
    list.Parent = details
    list.FillDirection = Enum.FillDirection.Vertical
    list.HorizontalAlignment = Enum.HorizontalAlignment.Center
    list.HorizontalFlex = Enum.UIFlexAlignment.None
    list.VerticalAlignment = Enum.VerticalAlignment.Top
    list.SortOrder = Enum.SortOrder.LayoutOrder
    list.Name = "list"
    list.Wraps = false
    list.Padding = UDim.new(0, 5)
    list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
    list.VerticalFlex = Enum.UIFlexAlignment.None
    local display_name = Instance.new("TextLabel")
    display_name.Parent = details
    display_name.LayoutOrder = 0
    display_name.FontSize = Enum.FontSize.Size18
    display_name.TextDirection = Enum.TextDirection.Auto
    display_name.Active = false
    display_name.Interactable = true
    display_name.TextStrokeTransparency = 1
    display_name.TextTruncate = Enum.TextTruncate.None
    display_name.SizeConstraint = Enum.SizeConstraint.RelativeXY
    display_name.ZIndex = 1
    display_name.BorderSizePixel = 0
    display_name.Draggable = false
    display_name.RichText = false
    display_name.SelectionOrder = 0
    display_name.TextYAlignment = Enum.TextYAlignment.Bottom
    display_name.TextScaled = false
    display_name.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    display_name.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
    display_name.BorderMode = Enum.BorderMode.Outline
    display_name.Selectable = false
    display_name.OpenTypeFeatures = ""
    display_name.AnchorPoint = Vector2.new(0, 0)
    display_name.BorderColor = BrickColor.new("Really black")
    display_name.Visible = true
    display_name.TextXAlignment = Enum.TextXAlignment.Center
    display_name.AutomaticSize = Enum.AutomaticSize.None
    display_name.Size = UDim2.new(1, 0, 0, 25)
    display_name.TextWrapped = false
    display_name.TextWrap = false
    display_name.TextTransparency = 0
    display_name.ClipsDescendants = false
    display_name.BorderColor3 = Color3.fromRGB(0, 0, 0)
    display_name.Text = Title
    display_name.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    display_name.LineHeight = 1
    display_name.Rotation = 0
    display_name.Font = Enum.Font.Unknown
    display_name.BackgroundTransparency = 1
    display_name.Position = UDim2.new(0, 0, 0, 0)
    display_name.TextSize = 18
    display_name.MaxVisibleGraphemes = -1
    display_name.TextColor3 = Color3.fromRGB(255, 255, 255)
    display_name.Name = "display_name"
    local username = Instance.new("TextLabel")
    username.Parent = details
    username.LayoutOrder = 0
    username.FontSize = Enum.FontSize.Size18
    username.TextDirection = Enum.TextDirection.Auto
    username.Active = false
    username.Interactable = true
    username.TextStrokeTransparency = 1
    username.TextTruncate = Enum.TextTruncate.None
    username.SizeConstraint = Enum.SizeConstraint.RelativeXY
    username.ZIndex = 1
    username.BorderSizePixel = 0
    username.Draggable = false
    username.RichText = false
    username.SelectionOrder = 0
    username.TextYAlignment = Enum.TextYAlignment.Center
    username.TextScaled = false
    username.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    username.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    username.BorderMode = Enum.BorderMode.Outline
    username.Selectable = false
    username.OpenTypeFeatures = ""
    username.AnchorPoint = Vector2.new(0, 0)
    username.BorderColor = BrickColor.new("Really black")
    username.Visible = true
    username.TextXAlignment = Enum.TextXAlignment.Center
    username.AutomaticSize = Enum.AutomaticSize.None
    username.Size = UDim2.new(1, 0, 0, 15)
    username.TextWrapped = false
    username.TextWrap = false
    username.TextTransparency = 0.5
    username.ClipsDescendants = false
    username.BorderColor3 = Color3.fromRGB(0, 0, 0)
    username.Text = Description
    username.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    username.LineHeight = 1
    username.Rotation = 0
    username.Font = Enum.Font.Unknown
    username.BackgroundTransparency = 1
    username.Position = UDim2.new(0, 0, 0, 0)
    username.TextSize = 15
    username.MaxVisibleGraphemes = -1
    username.TextColor3 = Color3.fromRGB(255, 255, 255)
    username.Name = "username"
    local list = Instance.new("UIListLayout")
    list.Parent = scroll
    list.FillDirection = Enum.FillDirection.Vertical
    list.HorizontalAlignment = Enum.HorizontalAlignment.Center
    list.HorizontalFlex = Enum.UIFlexAlignment.None
    list.VerticalAlignment = Enum.VerticalAlignment.Top
    list.SortOrder = Enum.SortOrder.LayoutOrder
    list.Name = "list"
    list.Wraps = false
    list.Padding = UDim.new(0, 10)
    list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
    list.VerticalFlex = Enum.UIFlexAlignment.None
    local Category = Instance.new("CanvasGroup")
    Category.Parent = list
    Category.LayoutOrder = 4
    Category.GroupTransparency = 0
    Category.BorderMode = Enum.BorderMode.Outline
    Category.Interactable = true
    Category.AnchorPoint = Vector2.new(0.5, 0)
    Category.BorderColor = BrickColor.new("Really black")
    Category.SizeConstraint = Enum.SizeConstraint.RelativeXY
    Category.ZIndex = 1
    Category.AutomaticSize = Enum.AutomaticSize.Y
    Category.Size = UDim2.new(1, -40, 0, 0)
    Category.Draggable = false
    Category.Visible = true
    Category.ClipsDescendants = true
    Category.GroupColor3 = Color3.fromRGB(255, 255, 255)
    Category.Name = "Category"
    Category.SelectionOrder = 0
    Category.Selectable = false
    Category.Rotation = 0
    Category.Transparency = 1
    Category.BackgroundTransparency = 1
    Category.Position = UDim2.new(0, 0, 0, 0)
    Category.Active = false
    Category.BorderColor3 = Color3.fromRGB(0, 0, 0)
    Category.BorderSizePixel = 0
    Category.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    local list = Instance.new("UIListLayout")
    list.Parent = Category
    list.FillDirection = Enum.FillDirection.Vertical
    list.HorizontalAlignment = Enum.HorizontalAlignment.Left
    list.HorizontalFlex = Enum.UIFlexAlignment.None
    list.VerticalAlignment = Enum.VerticalAlignment.Top
    list.SortOrder = Enum.SortOrder.LayoutOrder
    list.Name = "list"
    list.Wraps = false
    list.Padding = UDim.new(0, 1)
    list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
    list.VerticalFlex = Enum.UIFlexAlignment.None
    local Action = Instance.new("ImageButton")
    Action.Parent = list
    Action.LayoutOrder = 1
    Action.Active = true
    Action.Interactable = true
    Action.SizeConstraint = Enum.SizeConstraint.RelativeXY
    Action.ZIndex = 1
    Action.BorderSizePixel = 0
    Action.SliceCenter = Rect.new(512, 214, 512, 214)
    Action.Draggable = false
    Action.ScaleType = Enum.ScaleType.Slice
    Action.Modal = false
    Action.AutoButtonColor = true
    Action.Transparency = 0.6000000238418579
    Action.SelectionOrder = 0
    Action.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    Action.ImageTransparency = 0.6000000238418579
    Action.Selectable = true
    Action.AnchorPoint = Vector2.new(0, 0)
    Action.Image = ""
    Action.TileSize = UDim2.new(1, 0, 1, 0)
    Action.ImageRectSize = Vector2.new(0, 0)
    Action.ImageContent = Content.none
    Action.Selected = false
    Action.AutomaticSize = Enum.AutomaticSize.None
    Action.Size = UDim2.new(1, 0, 0, 45)
    Action.Visible = true
    Action.HoverImage = ""
    Action.Style = Enum.ButtonStyle.Custom
    Action.ClipsDescendants = false
    Action.BorderColor3 = Color3.fromRGB(0, 0, 0)
    Action.BorderMode = Enum.BorderMode.Outline
    Action.ImageColor3 = Color3.fromRGB(0, 0, 0)
    Action.PressedImage = ""
    Action.Rotation = 0
    Action.ImageRectOffset = Vector2.new(0, 0)
    Action.BackgroundTransparency = 0.6000000238418579
    Action.Position = UDim2.new(0, 0, 0, 0)
    Action.SliceScale = 0.11999999731779099
    Action.ResampleMode = Enum.ResamplerMode.Default
    Action.BorderColor = BrickColor.new("Really black")
    Action.Name = "Action"
    local label = Instance.new("TextLabel")
    label.Parent = Action
    label.LayoutOrder = 0
    label.FontSize = Enum.FontSize.Size18
    label.TextDirection = Enum.TextDirection.Auto
    label.Active = false
    label.Interactable = true
    label.TextStrokeTransparency = 1
    label.TextTruncate = Enum.TextTruncate.None
    label.SizeConstraint = Enum.SizeConstraint.RelativeXY
    label.ZIndex = 1
    label.BorderSizePixel = 0
    label.Draggable = false
    label.RichText = false
    label.SelectionOrder = 0
    label.TextYAlignment = Enum.TextYAlignment.Center
    label.TextScaled = false
    label.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    label.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    label.BorderMode = Enum.BorderMode.Outline
    label.Selectable = false
    label.OpenTypeFeatures = ""
    label.AnchorPoint = Vector2.new(0, 0.5)
    label.BorderColor = BrickColor.new("Really black")
    label.Visible = true
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.AutomaticSize = Enum.AutomaticSize.None
    label.Size = UDim2.new(1, -50, 1, 0)
    label.TextWrapped = false
    label.TextWrap = false
    label.TextTransparency = 0.20000000298023224
    label.ClipsDescendants = false
    label.BorderColor3 = Color3.fromRGB(0, 0, 0)
    label.Text = "Action"
    label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    label.LineHeight = 1
    label.Rotation = 0
    label.Font = Enum.Font.Unknown
    label.BackgroundTransparency = 1
    label.Position = UDim2.new(0, 0, 0.5, 0)
    label.TextSize = 16
    label.MaxVisibleGraphemes = -1
    label.TextColor3 = Color3.fromRGB(255, 255, 255)
    label.Name = "label"
    local padding = Instance.new("UIPadding")
    padding.Parent = Action
    padding.PaddingTop = UDim.new(0, 0)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 0)
    padding.PaddingLeft = UDim.new(0, 20)
    padding.PaddingRight = UDim.new(0, 20)
    local icon = Instance.new("ImageLabel")
    icon.Parent = Action
    icon.LayoutOrder = 0
    icon.Active = false
    icon.Interactable = true
    icon.SizeConstraint = Enum.SizeConstraint.RelativeXY
    icon.ZIndex = 1
    icon.BorderSizePixel = 0
    icon.SliceCenter = Rect.new(0, 0, 0, 0)
    icon.Draggable = false
    icon.ScaleType = Enum.ScaleType.Fit
    icon.Transparency = 1
    icon.SelectionOrder = 0
    icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    icon.ImageTransparency = 0.10000000149011612
    icon.Selectable = false
    icon.AnchorPoint = Vector2.new(1, 0.5)
    icon.Image = ""
    icon.TileSize = UDim2.new(1, 0, 1, 0)
    icon.BorderColor = BrickColor.new("Really black")
    icon.ImageContent = Content.none
    icon.AutomaticSize = Enum.AutomaticSize.None
    icon.Size = UDim2.new(0, 18, 0, 18)
    icon.ClipsDescendants = false
    icon.BorderColor3 = Color3.fromRGB(0, 0, 0)
    icon.Visible = true
    icon.ImageColor3 = Color3.fromRGB(255, 255, 255)
    icon.BorderMode = Enum.BorderMode.Outline
    icon.Rotation = 0
    icon.ImageRectOffset = Vector2.new(0, 0)
    icon.BackgroundTransparency = 1
    icon.Position = UDim2.new(1, 0, 0.5, 0)
    icon.SliceScale = 1
    icon.ImageRectSize = Vector2.new(0, 0)
    icon.ResampleMode = Enum.ResamplerMode.Default
    icon.Name = "icon"
    local scale = Instance.new("UIScale")
    scale.Parent = icon
    scale.Name = "scale"
    scale.Scale = 1
    local textbox = Instance.new("TextBox")
    textbox.Parent = Action
    textbox.MultiLine = false
    textbox.CursorPosition = 1
    textbox.LineHeight = 1
    textbox.Active = true
    textbox.Interactable = true
    textbox.TextStrokeTransparency = 1
    textbox.SelectionStart = -1
    textbox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
    textbox.SizeConstraint = Enum.SizeConstraint.RelativeXY
    textbox.ZIndex = 1
    textbox.BorderSizePixel = 0
    textbox.TextEditable = true
    textbox.Draggable = false
    textbox.RichText = false
    textbox.SelectionOrder = 0
    textbox.TextYAlignment = Enum.TextYAlignment.Center
    textbox.TextScaled = false
    textbox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    textbox.Visible = false
    textbox.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    textbox.TextXAlignment = Enum.TextXAlignment.Right
    textbox.BorderMode = Enum.BorderMode.Outline
    textbox.Selectable = true
    textbox.TextWrapped = false
    textbox.OpenTypeFeatures = ""
    textbox.TextWrap = false
    textbox.AnchorPoint = Vector2.new(1, 0.5)
    textbox.TextTruncate = Enum.TextTruncate.AtEnd
    textbox.TextTransparency = 0.4000000059604645
    textbox.BorderColor = BrickColor.new("Really black")
    textbox.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    textbox.PlaceholderText = ""
    textbox.AutomaticSize = Enum.AutomaticSize.None
    textbox.ShowNativeInput = true
    textbox.TextSize = 15
    textbox.TextDirection = Enum.TextDirection.Auto
    textbox.TextColor3 = Color3.fromRGB(255, 255, 255)
    textbox.ClipsDescendants = false
    textbox.BorderColor3 = Color3.fromRGB(0, 0, 0)
    textbox.Text = ""
    textbox.Size = UDim2.new(0, 100, 1, 0)
    textbox.LayoutOrder = 0
    textbox.Rotation = 0
    textbox.Font = Enum.Font.Unknown
    textbox.BackgroundTransparency = 1
    textbox.Position = UDim2.new(1, 0, 0.5, 0)
    textbox.FontSize = Enum.FontSize.Size18
    textbox.ClearTextOnFocus = true
    textbox.Name = "textbox"
    textbox.MaxVisibleGraphemes = -1
    local value = Instance.new("TextLabel")
    value.Parent = Action
    value.LayoutOrder = 0
    value.FontSize = Enum.FontSize.Size18
    value.TextDirection = Enum.TextDirection.Auto
    value.Active = false
    value.Interactable = true
    value.TextStrokeTransparency = 1
    value.TextTruncate = Enum.TextTruncate.None
    value.SizeConstraint = Enum.SizeConstraint.RelativeXY
    value.ZIndex = 1
    value.BorderSizePixel = 0
    value.Draggable = false
    value.RichText = false
    value.SelectionOrder = 0
    value.TextYAlignment = Enum.TextYAlignment.Center
    value.TextScaled = false
    value.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    value.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    value.BorderMode = Enum.BorderMode.Outline
    value.Selectable = false
    value.OpenTypeFeatures = ""
    value.AnchorPoint = Vector2.new(1, 0.5)
    value.BorderColor = BrickColor.new("Really black")
    value.Visible = true
    value.TextXAlignment = Enum.TextXAlignment.Right
    value.AutomaticSize = Enum.AutomaticSize.None
    value.Size = UDim2.new(1, -50, 1, 0)
    value.TextWrapped = false
    value.TextWrap = false
    value.TextTransparency = 0.699999988079071
    value.ClipsDescendants = false
    value.BorderColor3 = Color3.fromRGB(0, 0, 0)
    value.Text = ""
    value.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    value.LineHeight = 1
    value.Rotation = 0
    value.Font = Enum.Font.Unknown
    value.BackgroundTransparency = 1
    value.Position = UDim2.new(1, 0, 0.5, 0)
    value.TextSize = 16
    value.MaxVisibleGraphemes = -1
    value.TextColor3 = Color3.fromRGB(255, 255, 255)
    value.Name = "value"
    local corner = Instance.new("UICorner")
    corner.Parent = Category
    corner.Name = "corner"
    corner.CornerRadius = UDim.new(0, 12)
    local padding = Instance.new("UIPadding")
    padding.Parent = scroll
    padding.PaddingTop = UDim.new(0, 0)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 10)
    padding.PaddingLeft = UDim.new(0, 0)
    padding.PaddingRight = UDim.new(0, 0)
    local header = Instance.new("TextLabel")
    header.Parent = frame
    header.LayoutOrder = 0
    header.FontSize = Enum.FontSize.Size24
    header.TextDirection = Enum.TextDirection.Auto
    header.Active = false
    header.Interactable = true
    header.TextStrokeTransparency = 1
    header.TextTruncate = Enum.TextTruncate.None
    header.SizeConstraint = Enum.SizeConstraint.RelativeXY
    header.ZIndex = 2
    header.BorderSizePixel = 0
    header.Draggable = false
    header.RichText = false
    header.SelectionOrder = 0
    header.TextYAlignment = Enum.TextYAlignment.Center
    header.TextScaled = false
    header.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    header.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.SemiBold, Enum.FontStyle.Normal)
    header.BorderMode = Enum.BorderMode.Outline
    header.Selectable = false
    header.OpenTypeFeatures = ""
    header.AnchorPoint = Vector2.new(0.5, 0)
    header.BorderColor = BrickColor.new("Really black")
    header.Visible = true
    header.TextXAlignment = Enum.TextXAlignment.Center
    header.AutomaticSize = Enum.AutomaticSize.None
    header.Size = UDim2.new(1, 0, 0, 40)
    header.TextWrapped = false
    header.TextWrap = false
    header.TextTransparency = 0.10000000149011612
    header.ClipsDescendants = false
    header.BorderColor3 = Color3.fromRGB(0, 0, 0)
    header.Text = "Exo"
    header.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    header.LineHeight = 1
    header.Rotation = 0
    header.Font = Enum.Font.Unknown
    header.BackgroundTransparency = 1
    header.Position = UDim2.new(0.5, 0, 0, 0)
    header.TextSize = 22
    header.MaxVisibleGraphemes = -1
    header.TextColor3 = Color3.fromRGB(255, 255, 255)
    header.Name = "header"
    local close = Instance.new("ImageButton")
    close.Parent = frame
    close.LayoutOrder = 0
    close.Active = true
    close.Interactable = true
    close.SizeConstraint = Enum.SizeConstraint.RelativeXY
    close.ZIndex = 2
    close.BorderSizePixel = 0
    close.SliceCenter = Rect.new(0, 0, 0, 0)
    close.Draggable = false
    close.ScaleType = Enum.ScaleType.Stretch
    close.Modal = false
    close.AutoButtonColor = false
    close.Transparency = 0
    close.SelectionOrder = 0
    close.BackgroundColor3 = Color3.fromRGB(94, 98, 99)
    close.ImageTransparency = 0
    close.Selectable = true
    close.AnchorPoint = Vector2.new(1, 0)
    close.Image = ""
    close.TileSize = UDim2.new(1, 0, 1, 0)
    close.ImageRectSize = Vector2.new(0, 0)
    close.ImageContent = Content.none
    close.Selected = false
    close.AutomaticSize = Enum.AutomaticSize.None
    close.Size = UDim2.new(0, 30, 0, 30)
    close.Visible = true
    close.HoverImage = ""
    close.Style = Enum.ButtonStyle.Custom
    close.ClipsDescendants = false
    close.BorderColor3 = Color3.fromRGB(0, 0, 0)
    close.BorderMode = Enum.BorderMode.Outline
    close.ImageColor3 = Color3.fromRGB(255, 255, 255)
    close.PressedImage = ""
    close.Rotation = 0
    close.ImageRectOffset = Vector2.new(0, 0)
    close.BackgroundTransparency = 0
    close.Position = UDim2.new(1, -5, 0, 5)
    close.SliceScale = 1
    close.ResampleMode = Enum.ResamplerMode.Default
    close.BorderColor = BrickColor.new("Really black")
    close.Name = "close"

    close.MouseButton1Down:Connect(function()
        _G["Modal_Open"] = false
        modal_panel.ImageTransparency = 1
        game:GetService("TweenService"):Create(modal_panel.scale, TweenInfo.new(0.3), {Scale=0}):Play()
        wait(0.2)
        modal_panel:Destroy()
    end)

    close.MouseEnter:Connect(function()
        game:GetService("TweenService"):Create(close, TweenInfo.new(0.2), {BackgroundColor3=Color3.fromRGB(125, 125, 125)}):Play()
    end)
    close.MouseLeave:Connect(function()
        game:GetService("TweenService"):Create(close, TweenInfo.new(0.2), {BackgroundColor3=Color3.fromRGB(94, 98, 99)}):Play()
    end)

    local corner = Instance.new("UICorner")
    corner.Parent = close
    corner.Name = "corner"
    corner.CornerRadius = UDim.new(1, 0)
    local gradient = Instance.new("UIGradient")
    gradient.Parent = close
    gradient.Offset = Vector2.new(0, 0)
    gradient.Transparency =
        NumberSequence.new({NumberSequenceKeypoint.new(0, 0, 0), NumberSequenceKeypoint.new(1, 0.46875, 0)})
    gradient.Name = "gradient"
    gradient.Color =
        ColorSequence.new(
        {
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
            ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))
        }
    )
    gradient.Rotation = 0
    gradient.Enabled = false
    local icon = Instance.new("ImageLabel")
    icon.Parent = close
    icon.LayoutOrder = 0
    icon.Active = false
    icon.Interactable = true
    icon.SizeConstraint = Enum.SizeConstraint.RelativeXY
    icon.ZIndex = 2
    icon.BorderSizePixel = 0
    icon.SliceCenter = Rect.new(0, 0, 0, 0)
    icon.Draggable = false
    icon.ScaleType = Enum.ScaleType.Fit
    icon.Transparency = 1
    icon.SelectionOrder = 0
    icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    icon.ImageTransparency = 0.20000000298023224
    icon.Selectable = false
    icon.AnchorPoint = Vector2.new(0.5, 0.5)
    icon.Image = "rbxassetid://11293981586"
    icon.TileSize = UDim2.new(1, 0, 1, 0)
    icon.BorderColor = BrickColor.new("Really black")
    icon.ImageContent = Content.fromUri("rbxassetid://11293981586")
    icon.AutomaticSize = Enum.AutomaticSize.None
    icon.Size = UDim2.new(0, 16, 0, 16)
    icon.ClipsDescendants = false
    icon.BorderColor3 = Color3.fromRGB(0, 0, 0)
    icon.Visible = true
    icon.ImageColor3 = Color3.fromRGB(255, 255, 255)
    icon.BorderMode = Enum.BorderMode.Outline
    icon.Rotation = 0
    icon.ImageRectOffset = Vector2.new(0, 0)
    icon.BackgroundTransparency = 1
    icon.Position = UDim2.new(0.5, 0, 0.5, 0)
    icon.SliceScale = 1
    icon.ImageRectSize = Vector2.new(0, 0)
    icon.ResampleMode = Enum.ResamplerMode.Default
    icon.Name = "icon"
    local scale = Instance.new("UIScale")
    scale.Parent = icon
    scale.Name = "scale"
    scale.Scale = 1
    local fade = Instance.new("ImageLabel")
    fade.Parent = frame
    fade.LayoutOrder = 0
    fade.Active = false
    fade.Interactable = true
    fade.SizeConstraint = Enum.SizeConstraint.RelativeXY
    fade.ZIndex = 1
    fade.BorderSizePixel = 0
    fade.SliceCenter = Rect.new(512, 669, 576, 1024)
    fade.Draggable = false
    fade.ScaleType = Enum.ScaleType.Slice
    fade.Transparency = 1
    fade.SelectionOrder = 0
    fade.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
    fade.ImageTransparency = 0
    fade.Selectable = false
    fade.AnchorPoint = Vector2.new(0.5, 0)
    fade.Image = "rbxassetid://16286719854"
    fade.TileSize = UDim2.new(1, 0, 1, 0)
    fade.BorderColor = BrickColor.new("Really black")
    fade.ImageContent = Content.fromUri("rbxassetid://16286719854")
    fade.AutomaticSize = Enum.AutomaticSize.None
    fade.Size = UDim2.new(1, 20, 0, 60)
    fade.ClipsDescendants = false
    fade.BorderColor3 = Color3.fromRGB(0, 0, 0)
    fade.Visible = true
    fade.ImageColor3 = Color3.fromRGB(64, 66, 68)
    fade.BorderMode = Enum.BorderMode.Outline
    fade.Rotation = 0
    fade.ImageRectOffset = Vector2.new(0, 0)
    fade.BackgroundTransparency = 1
    fade.Position = UDim2.new(0.5, 0, 0, -10)
    fade.SliceScale = 1
    fade.ImageRectSize = Vector2.new(0, 0)
    fade.ResampleMode = Enum.ResamplerMode.Default
    fade.Name = "fade"
    local gradient = Instance.new("UIGradient")
    gradient.Parent = fade
    gradient.Offset = Vector2.new(0, 0)
    gradient.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0, 0), NumberSequenceKeypoint.new(1, 1, 0)})
    gradient.Name = "gradient"
    gradient.Color =
        ColorSequence.new(
        {
            ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
            ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))
        }
    )
    gradient.Rotation = 90
    gradient.Enabled = true
    local scale = Instance.new("UIScale")
    scale.Parent = frame
    scale.Name = "scale"
    scale.Scale = 1
    local corner = Instance.new("UICorner")
    corner.Parent = modal_panel
    corner.Name = "corner"
    corner.CornerRadius = UDim.new(0, 0)
    wait(0.2)
    _G["Modal_Open"] = true
    local newmodal = {modal=modal_panel}
    function newmodal:ButtonList()
        local ButtonList = Instance.new("Frame")
        ButtonList.Parent = self.modal.frame.scroll
        ButtonList.LayoutOrder = 2
        ButtonList.BorderMode = Enum.BorderMode.Outline
        ButtonList.Interactable = true
        ButtonList.AnchorPoint = Vector2.new(0.5, 0)
        ButtonList.BorderColor = BrickColor.new("Really black")
        ButtonList.SizeConstraint = Enum.SizeConstraint.RelativeXY
        ButtonList.ZIndex = 1
        ButtonList.AutomaticSize = Enum.AutomaticSize.None
        ButtonList.Size = UDim2.new(1, 0, 0, 185)
        ButtonList.Draggable = false
        ButtonList.Visible = true
        ButtonList.ClipsDescendants = false
        ButtonList.BorderColor3 = Color3.fromRGB(0, 0, 0)
        ButtonList.Selectable = false
        ButtonList.Style = Enum.FrameStyle.Custom
        ButtonList.SelectionOrder = 0
        ButtonList.Rotation = 0
        ButtonList.Transparency = 1
        ButtonList.BackgroundTransparency = 1
        ButtonList.Position = UDim2.new(0, 0, 0, 0)
        ButtonList.Active = false
        ButtonList.Name = "ButtonList"
        ButtonList.BorderSizePixel = 0
        ButtonList.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        local list = Instance.new("UIListLayout")
        list.Parent = ButtonList
        list.FillDirection = Enum.FillDirection.Vertical
        list.HorizontalAlignment = Enum.HorizontalAlignment.Left
        list.HorizontalFlex = Enum.UIFlexAlignment.None
        list.VerticalAlignment = Enum.VerticalAlignment.Top
        list.SortOrder = Enum.SortOrder.LayoutOrder
        list.Name = "list"
        list.Wraps = false
        list.Padding = UDim.new(0, 1)
        list.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
        list.VerticalFlex = Enum.UIFlexAlignment.None
        local padding = Instance.new("UIPadding")
        padding.Parent = ButtonList
        padding.PaddingTop = UDim.new(0, 0)
        padding.Name = "padding"
        padding.PaddingBottom = UDim.new(0, 0)
        padding.PaddingLeft = UDim.new(0, 20)
        padding.PaddingRight = UDim.new(0, 20)
        return ButtonList
    end
    return newmodal
end

function library:ModalLabel(modal, text)
    local Button = Instance.new("ImageButton")
    Button.Parent = modal
    Button.LayoutOrder = 2
    Button.Active = true
    Button.Interactable = true
    Button.SizeConstraint = Enum.SizeConstraint.RelativeXY
    Button.ZIndex = 1
    Button.BorderSizePixel = 0
    Button.SliceCenter = Rect.new(0, 61, 1024, 1024)
    Button.Draggable = false
    Button.ScaleType = Enum.ScaleType.Crop
    Button.Modal = false
    Button.AutoButtonColor = true
    Button.Transparency = 1
    Button.SelectionOrder = 0
    Button.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    Button.ImageTransparency = 0.6000000238418579
    Button.Selectable = true
    Button.AnchorPoint = Vector2.new(0, 0)
    Button.Image = "rbxassetid://16286719854"
    Button.TileSize = UDim2.new(1, 0, 1, 0)
    Button.ImageRectSize = Vector2.new(0, 0)
    Button.ImageContent = Content.fromUri("rbxassetid://16286719854")
    Button.Selected = false
    Button.AutomaticSize = Enum.AutomaticSize.None
    Button.Size = UDim2.new(1, 0, 0, 45)
    Button.Visible = true
    Button.HoverImage = ""
    Button.Style = Enum.ButtonStyle.Custom
    Button.ClipsDescendants = false
    Button.BorderColor3 = Color3.fromRGB(0, 0, 0)
    Button.BorderMode = Enum.BorderMode.Outline
    Button.ImageColor3 = Color3.fromRGB(0, 0, 0)
    Button.PressedImage = ""
    Button.Rotation = 0
    Button.ImageRectOffset = Vector2.new(0, 0)
    Button.BackgroundTransparency = 1
    Button.Position = UDim2.new(0, 0, 0, 0)
    Button.SliceScale = 0.05000000074505806
    Button.ResampleMode = Enum.ResamplerMode.Default
    Button.BorderColor = BrickColor.new("Really black")
    Button.Name = "Button"
    local label = Instance.new("TextLabel")
    label.Parent = Button
    label.LayoutOrder = 0
    label.FontSize = Enum.FontSize.Size18
    label.TextDirection = Enum.TextDirection.Auto
    label.Active = false
    label.Interactable = true
    label.TextStrokeTransparency = 1
    label.TextTruncate = Enum.TextTruncate.None
    label.SizeConstraint = Enum.SizeConstraint.RelativeXY
    label.ZIndex = 1
    label.BorderSizePixel = 0
    label.Draggable = false
    label.RichText = false
    label.SelectionOrder = 0
    label.TextYAlignment = Enum.TextYAlignment.Center
    label.TextScaled = false
    label.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    label.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    label.BorderMode = Enum.BorderMode.Outline
    label.Selectable = false
    label.OpenTypeFeatures = ""
    label.AnchorPoint = Vector2.new(0, 0.5)
    label.BorderColor = BrickColor.new("Really black")
    label.Visible = true
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.AutomaticSize = Enum.AutomaticSize.None
    label.Size = UDim2.new(1, -50, 1, 0)
    label.TextWrapped = false
    label.TextWrap = false
    label.TextTransparency = 0.20000000298023224
    label.ClipsDescendants = false
    label.BorderColor3 = Color3.fromRGB(0, 0, 0)
    label.Text = text
    label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    label.LineHeight = 1
    label.Rotation = 0
    label.Font = Enum.Font.Unknown
    label.BackgroundTransparency = 1
    label.Position = UDim2.new(0, 0, 0.5, 0)
    label.TextSize = 16
    label.MaxVisibleGraphemes = -1
    label.TextColor3 = Color3.fromRGB(255, 255, 255)
    label.Name = "label"
    local padding = Instance.new("UIPadding")
    padding.Parent = Button
    padding.PaddingTop = UDim.new(0, 0)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 0)
    padding.PaddingLeft = UDim.new(0, 20)
    padding.PaddingRight = UDim.new(0, 20)
    Button.MouseEnter:Connect(function()
        game:GetService("TweenService"):Create(Button, TweenInfo.new(0.2), {ImageColor3=Color3.fromRGB(125, 125, 125)}):Play()
    end)
    Button.MouseLeave:Connect(function()
        game:GetService("TweenService"):Create(Button, TweenInfo.new(0.2), {ImageColor3=Color3.fromRGB(0, 0, 0)}):Play()
    end)
end

function library:ModalButton(modal, text, Icon, callback)
    if not isIcon(Icon) then return end
    local Button = Instance.new("ImageButton")
    Button.Parent = modal
    Button.LayoutOrder = 2
    Button.Active = true
    Button.Interactable = true
    Button.SizeConstraint = Enum.SizeConstraint.RelativeXY
    Button.ZIndex = 1
    Button.BorderSizePixel = 0
    Button.SliceCenter = Rect.new(0, 61, 1024, 1024)
    Button.Draggable = false
    Button.ScaleType = Enum.ScaleType.Crop
    Button.Modal = false
    Button.AutoButtonColor = true
    Button.Transparency = 1
    Button.SelectionOrder = 0
    Button.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    Button.ImageTransparency = 0.6000000238418579
    Button.Selectable = true
    Button.AnchorPoint = Vector2.new(0, 0)
    Button.Image = "rbxassetid://16286719854"
    Button.TileSize = UDim2.new(1, 0, 1, 0)
    Button.ImageRectSize = Vector2.new(0, 0)
    Button.ImageContent = Content.fromUri("rbxassetid://16286719854")
    Button.Selected = false
    Button.AutomaticSize = Enum.AutomaticSize.None
    Button.Size = UDim2.new(1, 0, 0, 45)
    Button.Visible = true
    Button.HoverImage = ""
    Button.Style = Enum.ButtonStyle.Custom
    Button.ClipsDescendants = false
    Button.BorderColor3 = Color3.fromRGB(0, 0, 0)
    Button.BorderMode = Enum.BorderMode.Outline
    Button.ImageColor3 = Color3.fromRGB(0, 0, 0)
    Button.PressedImage = ""
    Button.Rotation = 0
    Button.ImageRectOffset = Vector2.new(0, 0)
    Button.BackgroundTransparency = 1
    Button.Position = UDim2.new(0, 0, 0, 0)
    Button.SliceScale = 0.05000000074505806
    Button.ResampleMode = Enum.ResamplerMode.Default
    Button.BorderColor = BrickColor.new("Really black")
    Button.Name = "Button"
    local label = Instance.new("TextLabel")
    label.Parent = Button
    label.LayoutOrder = 0
    label.FontSize = Enum.FontSize.Size18
    label.TextDirection = Enum.TextDirection.Auto
    label.Active = false
    label.Interactable = true
    label.TextStrokeTransparency = 1
    label.TextTruncate = Enum.TextTruncate.None
    label.SizeConstraint = Enum.SizeConstraint.RelativeXY
    label.ZIndex = 1
    label.BorderSizePixel = 0
    label.Draggable = false
    label.RichText = false
    label.SelectionOrder = 0
    label.TextYAlignment = Enum.TextYAlignment.Center
    label.TextScaled = false
    label.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    label.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    label.BorderMode = Enum.BorderMode.Outline
    label.Selectable = false
    label.OpenTypeFeatures = ""
    label.AnchorPoint = Vector2.new(0, 0.5)
    label.BorderColor = BrickColor.new("Really black")
    label.Visible = true
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.AutomaticSize = Enum.AutomaticSize.None
    label.Size = UDim2.new(1, -50, 1, 0)
    label.TextWrapped = false
    label.TextWrap = false
    label.TextTransparency = 0.20000000298023224
    label.ClipsDescendants = false
    label.BorderColor3 = Color3.fromRGB(0, 0, 0)
    label.Text = text
    label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    label.LineHeight = 1
    label.Rotation = 0
    label.Font = Enum.Font.Unknown
    label.BackgroundTransparency = 1
    label.Position = UDim2.new(0, 0, 0.5, 0)
    label.TextSize = 16
    label.MaxVisibleGraphemes = -1
    label.TextColor3 = Color3.fromRGB(255, 255, 255)
    label.Name = "label"
    local padding = Instance.new("UIPadding")
    padding.Parent = Button
    padding.PaddingTop = UDim.new(0, 0)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 0)
    padding.PaddingLeft = UDim.new(0, 20)
    padding.PaddingRight = UDim.new(0, 20)
    local icon = Instance.new("ImageLabel")
    icon.Parent = Button
    icon.LayoutOrder = 0
    icon.Active = false
    icon.Interactable = true
    icon.SizeConstraint = Enum.SizeConstraint.RelativeXY
    icon.ZIndex = 1
    icon.BorderSizePixel = 0
    icon.SliceCenter = Rect.new(0, 0, 0, 0)
    icon.Draggable = false
    icon.ScaleType = Enum.ScaleType.Stretch
    icon.Transparency = 1
    icon.SelectionOrder = 0
    icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    icon.ImageTransparency = 0.10000000149011612
    icon.Selectable = false
    icon.AnchorPoint = Vector2.new(1, 0.5)
        if Icon.Type == "NamedIcon" then
		print("Using named icon:", Icon.Name)
        local iconDef = Icon.Definition
        Icon = Spritesheets[iconDef.Image]
        icon.ImageRectSize = iconDef.ImageRectSize
        icon.ImageRectOffset = iconDef.ImageRectPosition
	else
		print("Using asset id:", Icon.Id)
        Icon = "rbxassetid://"..Icon.Id
	end
    icon.Image = Icon
    icon.TileSize = UDim2.new(1, 0, 1, 0)
    icon.BorderColor = BrickColor.new("Really black")
    icon.ImageContent = Content.fromUri(Icon)
    icon.AutomaticSize = Enum.AutomaticSize.None
    icon.Size = UDim2.new(0, 18, 0, 18)
    icon.ClipsDescendants = false
    icon.BorderColor3 = Color3.fromRGB(0, 0, 0)
    icon.Visible = true
    icon.ImageColor3 = Color3.fromRGB(255, 255, 255)
    icon.BorderMode = Enum.BorderMode.Outline
    icon.Rotation = 0
    icon.ImageRectOffset = Vector2.new(0, 0)
    icon.BackgroundTransparency = 1
    icon.Position = UDim2.new(1, 0, 0.5, 0)
    icon.SliceScale = 1
    icon.ImageRectSize = Vector2.new(0, 0)
    icon.ResampleMode = Enum.ResamplerMode.Default
    icon.Name = "icon"
    Button.MouseEnter:Connect(function()
        game:GetService("TweenService"):Create(Button, TweenInfo.new(0.2), {ImageColor3=Color3.fromRGB(125, 125, 125)}):Play()
    end)
    Button.MouseLeave:Connect(function()
        game:GetService("TweenService"):Create(Button, TweenInfo.new(0.2), {ImageColor3=Color3.fromRGB(0, 0, 0)}):Play()
    end)
    Button.MouseButton1Down:Connect(function()
        callback()
    end)
end

function library:ModalToggle(modal, text, callback)
    local Toggle = Instance.new("ImageButton")
    Toggle.Parent = modal
    Toggle.LayoutOrder = 1
    Toggle.Active = true
    Toggle.Interactable = true
    Toggle.SizeConstraint = Enum.SizeConstraint.RelativeXY
    Toggle.ZIndex = 1
    Toggle.BorderSizePixel = 0
    Toggle.SliceCenter = Rect.new(512, 214, 512, 214)
    Toggle.Draggable = false
    Toggle.ScaleType = Enum.ScaleType.Slice
    Toggle.Modal = false
    Toggle.AutoButtonColor = true
    Toggle.Transparency = 1
    Toggle.SelectionOrder = 0
    Toggle.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    Toggle.ImageTransparency = 0.6000000238418579
    Toggle.Selectable = true
    Toggle.AnchorPoint = Vector2.new(0, 0)
    Toggle.Image = "rbxassetid://16287196357"
    Toggle.TileSize = UDim2.new(1, 0, 1, 0)
    Toggle.ImageRectSize = Vector2.new(0, 0)
    Toggle.ImageContent = Content.fromUri("rbxassetid://16287196357")
    Toggle.Selected = false
    Toggle.AutomaticSize = Enum.AutomaticSize.None
    Toggle.Size = UDim2.new(1, 0, 0, 45)
    Toggle.Visible = true
    Toggle.HoverImage = ""
    Toggle.Style = Enum.ButtonStyle.Custom
    Toggle.ClipsDescendants = false
    Toggle.BorderColor3 = Color3.fromRGB(0, 0, 0)
    Toggle.BorderMode = Enum.BorderMode.Outline
    Toggle.ImageColor3 = Color3.fromRGB(0, 0, 0)
    Toggle.PressedImage = ""
    Toggle.Rotation = 0
    Toggle.ImageRectOffset = Vector2.new(0, 0)
    Toggle.BackgroundTransparency = 1
    Toggle.Position = UDim2.new(0, 0, 0, 0)
    Toggle.SliceScale = 0.11999999731779099
    Toggle.ResampleMode = Enum.ResamplerMode.Default
    Toggle.BorderColor = BrickColor.new("Really black")
    Toggle.Name = "Toggle"
    local label = Instance.new("TextLabel")
    label.Parent = Toggle
    label.LayoutOrder = 0
    label.FontSize = Enum.FontSize.Size18
    label.TextDirection = Enum.TextDirection.Auto
    label.Active = false
    label.Interactable = true
    label.TextStrokeTransparency = 1
    label.TextTruncate = Enum.TextTruncate.None
    label.SizeConstraint = Enum.SizeConstraint.RelativeXY
    label.ZIndex = 1
    label.BorderSizePixel = 0
    label.Draggable = false
    label.RichText = false
    label.SelectionOrder = 0
    label.TextYAlignment = Enum.TextYAlignment.Center
    label.TextScaled = false
    label.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    label.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
    label.BorderMode = Enum.BorderMode.Outline
    label.Selectable = false
    label.OpenTypeFeatures = ""
    label.AnchorPoint = Vector2.new(0, 0.5)
    label.BorderColor = BrickColor.new("Really black")
    label.Visible = true
    label.TextXAlignment = Enum.TextXAlignment.Left
    label.AutomaticSize = Enum.AutomaticSize.None
    label.Size = UDim2.new(1, -50, 1, 0)
    label.TextWrapped = false
    label.TextWrap = false
    label.TextTransparency = 0.20000000298023224
    label.ClipsDescendants = false
    label.BorderColor3 = Color3.fromRGB(0, 0, 0)
    label.Text = text
    label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    label.LineHeight = 1
    label.Rotation = 0
    label.Font = Enum.Font.Unknown
    label.BackgroundTransparency = 1
    label.Position = UDim2.new(0, 0, 0.5, 0)
    label.TextSize = 16
    label.MaxVisibleGraphemes = -1
    label.TextColor3 = Color3.fromRGB(255, 255, 255)
    label.Name = "label"
    local padding = Instance.new("UIPadding")
    padding.Parent = Toggle
    padding.PaddingTop = UDim.new(0, 0)
    padding.Name = "padding"
    padding.PaddingBottom = UDim.new(0, 0)
    padding.PaddingLeft = UDim.new(0, 20)
    padding.PaddingRight = UDim.new(0, 20)
    local icon = Instance.new("ImageLabel")
    icon.Parent = Toggle
    icon.LayoutOrder = 0
    icon.Active = false
    icon.Interactable = true
    icon.SizeConstraint = Enum.SizeConstraint.RelativeXY
    icon.ZIndex = 1
    icon.BorderSizePixel = 0
    icon.SliceCenter = Rect.new(0, 0, 0, 0)
    icon.Draggable = false
    icon.ScaleType = Enum.ScaleType.Stretch
    icon.Transparency = 1
    icon.SelectionOrder = 0
    icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    icon.ImageTransparency = 0.10000000149011612
    icon.Selectable = false
    icon.AnchorPoint = Vector2.new(1, 0.5)
    icon.Image = "http://www.roblox.com/asset/?id=16307805649"
    icon.TileSize = UDim2.new(1, 0, 1, 0)
    icon.BorderColor = BrickColor.new("Really black")
    icon.ImageContent = Content.fromUri("http://www.roblox.com/asset/?id=16307805649")
    icon.AutomaticSize = Enum.AutomaticSize.None
    icon.Size = UDim2.new(0, 18, 0, 18)
    icon.ClipsDescendants = false
    icon.BorderColor3 = Color3.fromRGB(0, 0, 0)
    icon.Visible = true
    icon.ImageColor3 = Color3.fromRGB(25,25,25)
    icon.BorderMode = Enum.BorderMode.Outline
    icon.Rotation = 0
    icon.ImageRectOffset = Vector2.new(0, 0)
    icon.BackgroundTransparency = 1
    icon.Position = UDim2.new(1, 0, 0.5, 0)
    icon.SliceScale = 1
    icon.ImageRectSize = Vector2.new(0, 0)
    icon.ResampleMode = Enum.ResamplerMode.Default
    icon.Name = "icon"
    Toggle.MouseEnter:Connect(function()
        game:GetService("TweenService"):Create(Toggle, TweenInfo.new(0.2), {ImageColor3=Color3.fromRGB(125, 125, 125)}):Play()
    end)
    Toggle.MouseLeave:Connect(function()
        game:GetService("TweenService"):Create(Toggle, TweenInfo.new(0.2), {ImageColor3=Color3.fromRGB(0, 0, 0)}):Play()
    end)
    if _G["Toggle_"..text..modal.parent.details.display_name.text] == nil then
        _G["Toggle_"..text..modal.parent.details.display_name.text] = false
    end
    if _G["Toggle_"..text..modal.parent.details.display_name.text] == true then
        icon.ImageColor3 = Color3.fromRGB(85, 255, 127)
    end
    if _G["Toggle_"..text..modal.parent.details.display_name.text] == false then
        icon.ImageColor3 = Color3.fromRGB(25, 25, 25)
    end
    Toggle.MouseButton1Down:Connect(function()
        if _G["Toggle_"..text..modal.parent.details.display_name.text] == false then
            _G["Toggle_"..text..modal.parent.details.display_name.text] = true
            icon.ImageColor3 = Color3.fromRGB(85, 255, 127)
            callback(true)
        else
            _G["Toggle_"..text..modal.parent.details.display_name.text] = false
            icon.ImageColor3 = Color3.fromRGB(25, 25, 25)
            callback(false)
        end
    end)
end

function library:AddBlur()
    for i,v in pairs(game:GetService("Lighting"):GetChildren()) do
        if v.Name == "Blur" then
            v:Destroy()
        end
    end
    local blur = Instance.new("BlurEffect", game:GetService("Lighting"))
end
function library:RemoveBlur()
    for i,v in pairs(game:GetService("Lighting"):GetChildren()) do
        if v.Name == "Blur" then
            v:Destroy()
        end
    end
    if game:GetService("Lighting"):FindFirstChild("Blur") then
        local blur = game:GetService("Lighting")["Blur"]
        game:GetService("TweenService"):Create(blur, TweenInfo.new(0.3), {Size=0}):Play()
        wait(0.2)
        blur:Destroy()
    end
end
function library:CloseUI()
    library.active = false
    library:RemoveBlur()
    for i,v in pairs(ModalFolder:GetChildren()) do
        game:GetService("TweenService"):Create(v.scale, TweenInfo.new(0.3), {Scale=0}):Play()
    end
    game:GetService("TweenService"):Create(frame.scale, TweenInfo.new(0.3), {Scale=0}):Play()
    wait(0.2)
    ScreenGui.Enabled = false
end
function library:OpenUI()
    library:AddBlur()
    wait(0.05)
    library.active = true
    ScreenGui.Enabled = true
    game:GetService("TweenService"):Create(frame.scale, TweenInfo.new(0.5), {Scale=1}):Play()
    for i,v in pairs(ModalFolder:GetChildren()) do
        game:GetService("TweenService"):Create(v.scale, TweenInfo.new(0.5), {Scale=1}):Play()
    end
    wait(0.2)
    ScreenGui.Enabled = true
end
function library:ToggleUI()
    if library.active then
        library:CloseUI()
    else 
        library:OpenUI()
    end
end
UIS.InputBegan:Connect(function(Input, Processed)
	if Input.KeyCode == Enum.KeyCode.Delete then 
		library:ToggleUI()
	end
end)
library:RemoveBlur()
library:AddBlur()

local Icons = {}

function Icons:Create(nameOrId)
	local iconData
	local isAssetId = tonumber(nameOrId) ~= nil
	
	if isAssetId then
		iconData = {
			Type = "AssetId",
			Id = tostring(nameOrId),
		}
	else
		local icon = IconLibrary[nameOrId]
		if not icon then
			error(("Unknown icon name: %s"):format(tostring(nameOrId)))
		end
		iconData = {
			Type = "NamedIcon",
			Name = nameOrId,
			Definition = icon,
		}
	end
	return setmetatable(iconData, { __type = "Icon" })
end

return library, Icons
